In [1]:
import pandas as pd
from pandas import MultiIndex

# Preparing LeftCompDaily

In [2]:
av_rates = ["av0.1", "av0.2", "av0.3", "av0.4", "av0.6", "av0.8"]

In [3]:
final_LeftCompDaily = pd.read_pickle("../results_csvs/scenarios_LeftCompDaily.pkl")
final_LeftCompDaily = final_LeftCompDaily["TOTAL"].drop(columns=["av0.5"])
final_LeftCompDaily.columns = MultiIndex.from_product([["LeftCompDaily"], final_LeftCompDaily.columns])
final_LeftCompDaily.dropna(inplace=True)

In [4]:
final_LeftCompDaily

                                LeftCompDaily                              \
                                        av0.1    av0.2    av0.3     av0.4
Control mean_speed_in_PTL 10 18       3771.36  3754.07  4506.08   5001.98
Control mean_speed_in_PTL 10 20       3702.08  3754.07  4506.08   5001.98
Control mean_speed_in_PTL 12 20        3622.7  3754.07  4506.08   5001.98
Control mean_speed_in_PTL 13 20       3702.08  3754.07  4506.08   5038.38
Control mean_speed_in_PTL 14 20       3702.08  3754.07  4506.08   5061.22
...                                       ...      ...      ...       ...
Trained_TreesSimFeatUnbounded         3766.14  3679.79  3914.57    4020.1
Trained_TreesSimFeatUnboundedWP       3627.94   3688.7  4052.28  3977.205
Trained_TreesSimFeatWP                3684.02  3700.01  3901.53   3590.37
Trained_XGBoostSimFeat                3678.77  3729.96  3639.04   3783.55
Trained_XGBoostSimFeatWP              3809.51  3765.58   3684.9   3527.79


                                   av0.6    av0.8
Control mean_speed_in_PTL 10 18  3913.36  3649.81
Control mean_speed_in_PTL 10 20  3915.56  3639.91
Control mean_speed_in_PTL 12 20  3863.04  3553.33
Control mean_speed_in_PTL 13 20  3808.12  3653.59
Control mean_speed_in_PTL 14 20  3783.92  3545.47
...                                  ...      ...
Trained_TreesSimFeatUnbounded    4248.16   4118.6
Trained_TreesSimFeatUnboundedWP  4004.26  4039.31
Trained_TreesSimFeatWP           3583.75   3717.8
Trained_XGBoostSimFeat           4219.48  4048.31
Trained_XGBoostSimFeatWP          3567.0  3737.67

[77 rows x 6 columns]

# Preparing LeftCompScenarios

In [5]:
final_LeftCompScenarios = pd.read_pickle("../results_csvs/scenarios_LeftCompScenarios.pkl")
final_LeftCompScenarios = final_LeftCompScenarios.drop(columns=["TOTAL"], level=0)
final_LeftCompScenarios.dropna(inplace=True)

In [6]:
final_LeftCompScenarios

                                RUSH_HOUR_EXT                             \
                                        av0.1    av0.2    av0.3    av0.4
Control mean_speed_in_PTL 10 18        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 10 20        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 12 20        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 13 20        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 14 20        489.46  494.595   537.17  596.745
...                                       ...      ...      ...      ...
Trained_RFSimFeat                     548.415   488.69  513.045    501.7
Trained_Trees                          528.52  542.755  533.695  580.415
Trained_TreesSimFeat                  503.065  523.535  538.735  507.155
Trained_TreesSimFeatUnbounded         511.525    532.8  535.925  499.145
Trained_XGBoostSimFeat                 502.42  492.775  516.815   529.41

                                                      PEAK                    \
                                   av0.6    av0.8    av0.1    av0.2    av0.3
Control mean_speed_in_PTL 10 18   532.73   523.66  758.005  767.205  810.835
Control mean_speed_in_PTL 10 20   532.73   523.66  758.005  767.205  810.835
Control mean_speed_in_PTL 12 20  516.375  559.095  758.005  767.205  810.835
Control mean_speed_in_PTL 13 20  516.375   556.84  758.005  767.205  810.835
Control mean_speed_in_PTL 14 20   526.67  548.925  758.005  767.205  810.835
...                                  ...      ...      ...      ...      ...
Trained_RFSimFeat                 523.28   571.18   780.08   742.15   815.16
Trained_Trees                     552.47   560.55  768.595   773.59  762.235
Trained_TreesSimFeat             513.455  490.215   804.35   757.64   782.02
Trained_TreesSimFeatUnbounded     543.32  556.025   790.43   770.89   769.37
Trained_XGBoostSimFeat           557.205    545.5  801.805  782.475  798.625

                                          ... WEEKEND                          \
                                   av0.4  ...   av0.3   av0.4   av0.6   av0.8
Control mean_speed_in_PTL 10 18  817.845  ...  18.415  18.225   16.98  17.695
Control mean_speed_in_PTL 10 20  817.845  ...  18.415  18.225   16.98  17.695
Control mean_speed_in_PTL 12 20  817.845  ...  18.415  18.225  17.185   17.35
Control mean_speed_in_PTL 13 20    835.5  ...  18.415  19.035  21.515   21.08
Control mean_speed_in_PTL 14 20    835.5  ...   18.28  19.035   17.68   18.64
...                                  ...  ...     ...     ...     ...     ...
Trained_RFSimFeat                829.485  ...   20.78  21.215  19.405   19.04
Trained_Trees                    824.465  ...  22.325  21.865   21.26   21.19
Trained_TreesSimFeat              799.96  ...   21.68  21.335  20.885  20.425
Trained_TreesSimFeatUnbounded    810.985  ...   19.63  21.185   20.45  19.945
Trained_XGBoostSimFeat           810.605  ...  20.615  20.855  21.125   21.02

                                MODERATE_RUSH_HOUR                             \
                                             av0.1    av0.2    av0.3    av0.4
Control mean_speed_in_PTL 10 18              246.2  249.425  380.935  409.625
Control mean_speed_in_PTL 10 20              246.2  249.425  380.935  409.625
Control mean_speed_in_PTL 12 20              246.2  249.425  380.935  409.625
Control mean_speed_in_PTL 13 20              246.2  249.425  380.935   405.04
Control mean_speed_in_PTL 14 20              246.2  249.425  360.275   405.04
...                                            ...      ...      ...      ...
Trained_RFSimFeat                          274.655  283.865  295.095   273.26
Trained_Trees                              260.215   279.96   358.43   354.97
Trained_TreesSimFeat                        282.84   275.97    286.6  273.255
Trained_TreesSimFeatUnbounded               281.77  272.345   300.18    296.9
Trained_XGBoostSimFeat                      282.38  269.155   286.66  295.175


                                   av0.6    av0.8
Control mean_speed_in_PTL 10 18   324.65   296.21
Control mean_speed_in_PTL 10 20  319.555    295.7
Control mean_speed_in_PTL 12 20  300.065   313.68
Control mean_speed_in_PTL 13 20    310.5    297.3
Control mean_speed_in_PTL 14 20  316.945   299.78
...                                  ...      ...
Trained_RFSimFeat                 309.86    324.4
Trained_Trees                     298.77   305.28
Trained_TreesSimFeat             268.425  262.705
Trained_TreesSimFeatUnbounded    298.655   296.97
Trained_XGBoostSimFeat            315.38  308.185

[71 rows x 30 columns]

# Preparing ClosedLeftCompScenarios

In [7]:
ClosedLeftCompScenarios = pd.read_pickle("../results_csvs/scenarios_ClosedLeftCompScenarios.pkl")
ClosedLeftCompScenarios = ClosedLeftCompScenarios.drop(columns=["TOTAL"], level=0)
ClosedLeftCompScenarios.dropna(inplace=True)

In [8]:
new_CloseLeftCompScenariosColumns = [("Closed_"+col[0], col[1]) for col in ClosedLeftCompScenarios.columns]
final_ClosedLeftCompScenarios = ClosedLeftCompScenarios.copy()
final_ClosedLeftCompScenarios.columns = MultiIndex.from_tuples(new_CloseLeftCompScenariosColumns)

In [9]:
final_ClosedLeftCompScenarios

                                Closed_RUSH_HOUR_EXT                    \
                                               av0.1    av0.2    av0.3
Control mean_speed_in_PTL 10 18               518.74   500.18  503.065
Control mean_speed_in_PTL 10 20               518.74   500.18  503.065
Control mean_speed_in_PTL 12 20               518.74   500.18  503.065
Control mean_speed_in_PTL 13 20               518.74   500.18  503.065
Control mean_speed_in_PTL 14 20               518.74   500.18  503.065
...                                              ...      ...      ...
Trained_TreesSimFeatUnbounded                 518.76   500.61   497.83
Trained_TreesSimFeatUnboundedWP              509.355  485.375   506.13
Trained_TreesSimFeatWP                       527.175  495.265  492.595
Trained_XGBoostSimFeat                        512.05  512.145    501.6
Trained_XGBoostSimFeatWP                      502.14  522.665   487.54

                                                           Closed_PEAK  \
                                   av0.4    av0.6    av0.8       av0.1
Control mean_speed_in_PTL 10 18   569.81    568.7  566.885      783.11
Control mean_speed_in_PTL 10 20   569.81    568.7  566.885      783.11
Control mean_speed_in_PTL 12 20   569.81  562.555  545.345      783.11
Control mean_speed_in_PTL 13 20   569.81   560.36   536.38      783.11
Control mean_speed_in_PTL 14 20   569.81   560.36   525.16      783.11
...                                  ...      ...      ...         ...
Trained_TreesSimFeatUnbounded    525.485  526.635   527.78      753.99
Trained_TreesSimFeatUnboundedWP   509.91  512.485  531.965      782.18
Trained_TreesSimFeatWP           524.275  548.235  505.055     762.765
Trained_XGBoostSimFeat           496.235   545.54   541.81      775.52
Trained_XGBoostSimFeatWP         509.525  532.205  512.385     783.285

                                                            ...  \
                                   av0.2    av0.3    av0.4  ...
Control mean_speed_in_PTL 10 18   741.63  810.795   804.49  ...
Control mean_speed_in_PTL 10 20   741.63  810.795   804.49  ...
Control mean_speed_in_PTL 12 20   741.63  810.795   804.49  ...
Control mean_speed_in_PTL 13 20   741.63  810.795   804.49  ...
Control mean_speed_in_PTL 14 20  795.315  810.795   804.49  ...
...                                  ...      ...      ...  ...
Trained_TreesSimFeatUnbounded    766.955  772.195   781.52  ...
Trained_TreesSimFeatUnboundedWP  776.495  758.755  763.985  ...
Trained_TreesSimFeatWP            771.83   779.99  784.835  ...
Trained_XGBoostSimFeat            769.89  794.315   842.52  ...
Trained_XGBoostSimFeatWP          775.03   779.51   821.32  ...

                                Closed_WEEKEND                          \
                                         av0.3   av0.4   av0.6   av0.8
Control mean_speed_in_PTL 10 18          19.96  19.255  18.255  19.115
Control mean_speed_in_PTL 10 20          19.96  19.255  18.255  19.115
Control mean_speed_in_PTL 12 20          19.02  19.255   18.31  18.745
Control mean_speed_in_PTL 13 20          19.02  19.255  19.845   19.59
Control mean_speed_in_PTL 14 20          19.02   18.72   18.71   18.89
...                                        ...     ...     ...     ...
Trained_TreesSimFeatUnbounded            20.82    20.4  20.685   21.48
Trained_TreesSimFeatUnboundedWP         20.365   20.67  20.235   19.97
Trained_TreesSimFeatWP                   20.05  18.965   17.92   19.02
Trained_XGBoostSimFeat                   21.52   22.06   20.83   20.69
Trained_XGBoostSimFeatWP                 21.32   20.85   19.98  21.015

                                Closed_MODERATE_RUSH_HOUR                    \
                                                    av0.1    av0.2    av0.3
Control mean_speed_in_PTL 10 18                    269.08   273.84   343.16
Control mean_speed_in_PTL 10 20                    269.08   273.84   343.16
Control mean_speed_in_PTL 12 20                    269.08   273.84   371.25
Control mean_speed_in_PTL 13 20                    269.08   273.84   371.25
Control mean_speed_in_PTL 14 20                    269.08   265.25   371.25
...                                                   ...      ...      ...
Trained_TreesSimFeatUnbounded                     258.225  267.825  297.715
Trained_TreesSimFeatUnboundedWP                   301.155   271.57  269.585
Trained_TreesSimFeatWP                             279.58   273.82  273.995
Trained_XGBoostSimFeat                            273.455  290.165  285.615
Trained_XGBoostSimFeatWP                           271.73  275.865   282.78


                                   av0.4    av0.6    av0.8
Control mean_speed_in_PTL 10 18   358.96   332.22  311.625
Control mean_speed_in_PTL 10 20   358.96   332.22  313.405
Control mean_speed_in_PTL 12 20  359.155  343.815  305.105
Control mean_speed_in_PTL 13 20   361.51  340.785  297.715
Control mean_speed_in_PTL 14 20    374.0   331.85  295.535
...                                  ...      ...      ...
Trained_TreesSimFeatUnbounded    271.675  273.715  284.665
Trained_TreesSimFeatUnboundedWP   289.85   284.77   287.86
Trained_TreesSimFeatWP            273.02   265.87   282.95
Trained_XGBoostSimFeat            272.95  298.055   308.02
Trained_XGBoostSimFeatWP          291.17  303.765  284.435

[77 rows x 30 columns]

# Creating the final results table

In [10]:
final_results_index =  ["NO PTL", "BUS-ONLY PTL",
                        "Best Daily HOV policy", "Best Daily HOV policy NAME",
                        "Best HOV policy per scenario", "Best HOV policy per scenario NAME",
                        "Best Daily StaticNumFL", "Best Daily StaticNumFL NAME",
                        "Best StaticNumFL per scenario", "Best StaticNumFL per scenario NAME",
                        "Best Daily Dynamic Policy", "Best Daily Dynamic Policy NAME",
                        "Best Dynamic Policy per scenario", "Best Dynamic Policy per scenario NAME"]
LeftCompDaily_empty = pd.DataFrame(columns=final_LeftCompDaily.columns, index=final_results_index)
LeftCompScenarios_empty = pd.DataFrame(columns=final_LeftCompScenarios.columns, index=final_results_index)
ClosedLeftCompScenarios_empty = pd.DataFrame(columns=final_ClosedLeftCompScenarios.columns, index=final_results_index)
final_results = pd.concat([LeftCompDaily_empty, LeftCompScenarios_empty, ClosedLeftCompScenarios_empty], axis=1)

In [11]:
final_results

                                      LeftCompDaily                          \
                                              av0.1 av0.2 av0.3 av0.4 av0.6
NO PTL                                          NaN   NaN   NaN   NaN   NaN
BUS-ONLY PTL                                    NaN   NaN   NaN   NaN   NaN
Best Daily HOV policy                           NaN   NaN   NaN   NaN   NaN
Best Daily HOV policy NAME                      NaN   NaN   NaN   NaN   NaN
Best HOV policy per scenario                    NaN   NaN   NaN   NaN   NaN
Best HOV policy per scenario NAME               NaN   NaN   NaN   NaN   NaN
Best Daily StaticNumFL                          NaN   NaN   NaN   NaN   NaN
Best Daily StaticNumFL NAME                     NaN   NaN   NaN   NaN   NaN
Best StaticNumFL per scenario                   NaN   NaN   NaN   NaN   NaN
Best StaticNumFL per scenario NAME              NaN   NaN   NaN   NaN   NaN
Best Daily Dynamic Policy                       NaN   NaN   NaN   NaN   NaN
Best Daily Dynamic Policy NAME                  NaN   NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario                NaN   NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario NAME           NaN   NaN   NaN   NaN   NaN

                                            RUSH_HOUR_EXT                    \
                                      av0.8         av0.1 av0.2 av0.3 av0.4
NO PTL                                  NaN           NaN   NaN   NaN   NaN
BUS-ONLY PTL                            NaN           NaN   NaN   NaN   NaN
Best Daily HOV policy                   NaN           NaN   NaN   NaN   NaN
Best Daily HOV policy NAME              NaN           NaN   NaN   NaN   NaN
Best HOV policy per scenario            NaN           NaN   NaN   NaN   NaN
Best HOV policy per scenario NAME       NaN           NaN   NaN   NaN   NaN
Best Daily StaticNumFL                  NaN           NaN   NaN   NaN   NaN
Best Daily StaticNumFL NAME             NaN           NaN   NaN   NaN   NaN
Best StaticNumFL per scenario           NaN           NaN   NaN   NaN   NaN
Best StaticNumFL per scenario NAME      NaN           NaN   NaN   NaN   NaN
Best Daily Dynamic Policy               NaN           NaN   NaN   NaN   NaN
Best Daily Dynamic Policy NAME          NaN           NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario        NaN           NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario NAME   NaN           NaN   NaN   NaN   NaN

                                       ... Closed_WEEKEND                    \
                                       ...          av0.3 av0.4 av0.6 av0.8
NO PTL                                 ...            NaN   NaN   NaN   NaN
BUS-ONLY PTL                           ...            NaN   NaN   NaN   NaN
Best Daily HOV policy                  ...            NaN   NaN   NaN   NaN
Best Daily HOV policy NAME             ...            NaN   NaN   NaN   NaN
Best HOV policy per scenario           ...            NaN   NaN   NaN   NaN
Best HOV policy per scenario NAME      ...            NaN   NaN   NaN   NaN
Best Daily StaticNumFL                 ...            NaN   NaN   NaN   NaN
Best Daily StaticNumFL NAME            ...            NaN   NaN   NaN   NaN
Best StaticNumFL per scenario          ...            NaN   NaN   NaN   NaN
Best StaticNumFL per scenario NAME     ...            NaN   NaN   NaN   NaN
Best Daily Dynamic Policy              ...            NaN   NaN   NaN   NaN
Best Daily Dynamic Policy NAME         ...            NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario       ...            NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario NAME  ...            NaN   NaN   NaN   NaN

                                      Closed_MODERATE_RUSH_HOUR              \
                                                          av0.1 av0.2 av0.3
NO PTL                                                      NaN   NaN   NaN
BUS-ONLY PTL                                                NaN   NaN   NaN
Best Daily HOV policy                                       NaN   NaN   NaN
Best Daily HOV policy NAME                                  NaN   NaN   NaN
Best HOV policy per scenario                                NaN   NaN   NaN
Best HOV policy per scenario NAME                           NaN   NaN   NaN
Best Daily StaticNumFL                                      NaN   NaN   NaN
Best Daily StaticNumFL NAME                                 NaN   NaN   NaN
Best StaticNumFL per scenario                               NaN   NaN   NaN
Best StaticNumFL per scenario NAME                          NaN   NaN   NaN
Best Daily Dynamic Policy                                   NaN   NaN   NaN
Best Daily Dynamic Policy NAME                              NaN   NaN   NaN
Best Dynamic Policy per scenario                            NaN   NaN   NaN
Best Dynamic Policy per scenario NAME                       NaN   NaN   NaN


                                      av0.4 av0.6 av0.8
NO PTL                                  NaN   NaN   NaN
BUS-ONLY PTL                            NaN   NaN   NaN
Best Daily HOV policy                   NaN   NaN   NaN
Best Daily HOV policy NAME              NaN   NaN   NaN
Best HOV policy per scenario            NaN   NaN   NaN
Best HOV policy per scenario NAME       NaN   NaN   NaN
Best Daily StaticNumFL                  NaN   NaN   NaN
Best Daily StaticNumFL NAME             NaN   NaN   NaN
Best StaticNumFL per scenario           NaN   NaN   NaN
Best StaticNumFL per scenario NAME      NaN   NaN   NaN
Best Daily Dynamic Policy               NaN   NaN   NaN
Best Daily Dynamic Policy NAME          NaN   NaN   NaN
Best Dynamic Policy per scenario        NaN   NaN   NaN
Best Dynamic Policy per scenario NAME   NaN   NaN   NaN

[14 rows x 66 columns]

# adding no ptl and bus only ptl

In [12]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["NO PTL",col] = final_LeftCompScenarios.loc["Plus_1",col]
        final_results.loc["BUS-ONLY PTL",col] = final_LeftCompScenarios.loc["Nothing",col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["NO PTL",col] = final_LeftCompDaily.loc["Plus_1",col]
        final_results.loc["BUS-ONLY PTL",col] = final_LeftCompDaily.loc["Nothing",col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["NO PTL",col] = final_ClosedLeftCompScenarios.loc["Plus_1",col]
        final_results.loc["BUS-ONLY PTL",col] = final_ClosedLeftCompScenarios.loc["Nothing",col]

In [13]:
final_results

                                      LeftCompDaily                    \
                                              av0.1    av0.2    av0.3
NO PTL                                      4299.88  4300.38  4306.26
BUS-ONLY PTL                                3959.38  3959.71  3962.75
Best Daily HOV policy                           NaN      NaN      NaN
Best Daily HOV policy NAME                      NaN      NaN      NaN
Best HOV policy per scenario                    NaN      NaN      NaN
Best HOV policy per scenario NAME               NaN      NaN      NaN
Best Daily StaticNumFL                          NaN      NaN      NaN
Best Daily StaticNumFL NAME                     NaN      NaN      NaN
Best StaticNumFL per scenario                   NaN      NaN      NaN
Best StaticNumFL per scenario NAME              NaN      NaN      NaN
Best Daily Dynamic Policy                       NaN      NaN      NaN
Best Daily Dynamic Policy NAME                  NaN      NaN      NaN
Best Dynamic Policy per scenario                NaN      NaN      NaN
Best Dynamic Policy per scenario NAME           NaN      NaN      NaN

                                                                  \
                                         av0.4    av0.6    av0.8
NO PTL                                 4306.22  4300.79   4299.4
BUS-ONLY PTL                           3964.21  3961.77  3958.67
Best Daily HOV policy                      NaN      NaN      NaN
Best Daily HOV policy NAME                 NaN      NaN      NaN
Best HOV policy per scenario               NaN      NaN      NaN
Best HOV policy per scenario NAME          NaN      NaN      NaN
Best Daily StaticNumFL                     NaN      NaN      NaN
Best Daily StaticNumFL NAME                NaN      NaN      NaN
Best StaticNumFL per scenario              NaN      NaN      NaN
Best StaticNumFL per scenario NAME         NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN
Best Daily Dynamic Policy NAME             NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN
Best Dynamic Policy per scenario NAME      NaN      NaN      NaN

                                      RUSH_HOUR_EXT                            \
                                              av0.1    av0.2    av0.3   av0.4
NO PTL                                       517.95   520.21  517.565  517.64
BUS-ONLY PTL                                523.465  527.125  527.125  531.82
Best Daily HOV policy                           NaN      NaN      NaN     NaN
Best Daily HOV policy NAME                      NaN      NaN      NaN     NaN
Best HOV policy per scenario                    NaN      NaN      NaN     NaN
Best HOV policy per scenario NAME               NaN      NaN      NaN     NaN
Best Daily StaticNumFL                          NaN      NaN      NaN     NaN
Best Daily StaticNumFL NAME                     NaN      NaN      NaN     NaN
Best StaticNumFL per scenario                   NaN      NaN      NaN     NaN
Best StaticNumFL per scenario NAME              NaN      NaN      NaN     NaN
Best Daily Dynamic Policy                       NaN      NaN      NaN     NaN
Best Daily Dynamic Policy NAME                  NaN      NaN      NaN     NaN
Best Dynamic Policy per scenario                NaN      NaN      NaN     NaN
Best Dynamic Policy per scenario NAME           NaN      NaN      NaN     NaN

                                       ... Closed_WEEKEND                 \
                                       ...          av0.3   av0.4  av0.6
NO PTL                                 ...          20.06   20.38  19.78
BUS-ONLY PTL                           ...          21.19  21.605  20.67
Best Daily HOV policy                  ...            NaN     NaN    NaN
Best Daily HOV policy NAME             ...            NaN     NaN    NaN
Best HOV policy per scenario           ...            NaN     NaN    NaN
Best HOV policy per scenario NAME      ...            NaN     NaN    NaN
Best Daily StaticNumFL                 ...            NaN     NaN    NaN
Best Daily StaticNumFL NAME            ...            NaN     NaN    NaN
Best StaticNumFL per scenario          ...            NaN     NaN    NaN
Best StaticNumFL per scenario NAME     ...            NaN     NaN    NaN
Best Daily Dynamic Policy              ...            NaN     NaN    NaN
Best Daily Dynamic Policy NAME         ...            NaN     NaN    NaN
Best Dynamic Policy per scenario       ...            NaN     NaN    NaN
Best Dynamic Policy per scenario NAME  ...            NaN     NaN    NaN

                                             Closed_MODERATE_RUSH_HOUR  \
                                       av0.8                     av0.1
NO PTL                                 19.98                   308.725
BUS-ONLY PTL                           21.18                     286.1
Best Daily HOV policy                    NaN                       NaN
Best Daily HOV policy NAME               NaN                       NaN
Best HOV policy per scenario             NaN                       NaN
Best HOV policy per scenario NAME        NaN                       NaN
Best Daily StaticNumFL                   NaN                       NaN
Best Daily StaticNumFL NAME              NaN                       NaN
Best StaticNumFL per scenario            NaN                       NaN
Best StaticNumFL per scenario NAME       NaN                       NaN
Best Daily Dynamic Policy                NaN                       NaN
Best Daily Dynamic Policy NAME           NaN                       NaN
Best Dynamic Policy per scenario         NaN                       NaN
Best Dynamic Policy per scenario NAME    NaN                       NaN

                                                                          \
                                         av0.2   av0.3    av0.4    av0.6
NO PTL                                 307.755  311.81  313.755  310.965
BUS-ONLY PTL                            284.25  288.21   289.69  285.615
Best Daily HOV policy                      NaN     NaN      NaN      NaN
Best Daily HOV policy NAME                 NaN     NaN      NaN      NaN
Best HOV policy per scenario               NaN     NaN      NaN      NaN
Best HOV policy per scenario NAME          NaN     NaN      NaN      NaN
Best Daily StaticNumFL                     NaN     NaN      NaN      NaN
Best Daily StaticNumFL NAME                NaN     NaN      NaN      NaN
Best StaticNumFL per scenario              NaN     NaN      NaN      NaN
Best StaticNumFL per scenario NAME         NaN     NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN     NaN      NaN      NaN
Best Daily Dynamic Policy NAME             NaN     NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN     NaN      NaN      NaN
Best Dynamic Policy per scenario NAME      NaN     NaN      NaN      NaN


                                         av0.8
NO PTL                                 305.155
BUS-ONLY PTL                            289.49
Best Daily HOV policy                      NaN
Best Daily HOV policy NAME                 NaN
Best HOV policy per scenario               NaN
Best HOV policy per scenario NAME          NaN
Best Daily StaticNumFL                     NaN
Best Daily StaticNumFL NAME                NaN
Best StaticNumFL per scenario              NaN
Best StaticNumFL per scenario NAME         NaN
Best Daily Dynamic Policy                  NaN
Best Daily Dynamic Policy NAME             NaN
Best Dynamic Policy per scenario           NaN
Best Dynamic Policy per scenario NAME      NaN

[14 rows x 66 columns]

# Adding best daily HOV policy

In [18]:
def row_with_max_min_count(df):
    min_values = df.min()
    is_min = df.eq(min_values)
    min_count_per_row = is_min.sum(axis=1)
    row_with_most_min_values = min_count_per_row.idxmax()
    return row_with_most_min_values

In [26]:
HOVs = ["Plus_1", "Plus_2", "Plus_3", "Plus_4", "Plus_5"]
LeftCompDaily_HOVs =  final_LeftCompDaily.loc[HOVs]
LeftCompDaily_HOVs_idx = row_with_max_min_count(LeftCompDaily_HOVs)

final_results.loc["Best Daily HOV policy NAME"] = LeftCompDaily_HOVs_idx
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Daily HOV policy",col] = final_LeftCompScenarios.loc[LeftCompDaily_HOVs_idx,col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Daily HOV policy",col] = final_LeftCompDaily.loc[LeftCompDaily_HOVs_idx,col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Daily HOV policy",col] = final_ClosedLeftCompScenarios.loc[LeftCompDaily_HOVs_idx,col]

In [27]:
final_results

                                      LeftCompDaily                    \
                                              av0.1    av0.2    av0.3
NO PTL                                      4299.88  4300.38  4306.26
BUS-ONLY PTL                                3959.38  3959.71  3962.75
Best Daily HOV policy                       3523.02  3529.48  3490.59
Best Daily HOV policy NAME                   Plus_3   Plus_3   Plus_3
Best HOV policy per scenario                    NaN      NaN      NaN
Best HOV policy per scenario NAME               NaN      NaN      NaN
Best Daily StaticNumFL                          NaN      NaN      NaN
Best Daily StaticNumFL NAME                     NaN      NaN      NaN
Best StaticNumFL per scenario                   NaN      NaN      NaN
Best StaticNumFL per scenario NAME              NaN      NaN      NaN
Best Daily Dynamic Policy                       NaN      NaN      NaN
Best Daily Dynamic Policy NAME                  NaN      NaN      NaN
Best Dynamic Policy per scenario                NaN      NaN      NaN
Best Dynamic Policy per scenario NAME           NaN      NaN      NaN

                                                                  \
                                         av0.4    av0.6    av0.8
NO PTL                                 4306.22  4300.79   4299.4
BUS-ONLY PTL                           3964.21  3961.77  3958.67
Best Daily HOV policy                  3597.59  3636.39  3581.58
Best Daily HOV policy NAME              Plus_3   Plus_3   Plus_3
Best HOV policy per scenario               NaN      NaN      NaN
Best HOV policy per scenario NAME          NaN      NaN      NaN
Best Daily StaticNumFL                     NaN      NaN      NaN
Best Daily StaticNumFL NAME                NaN      NaN      NaN
Best StaticNumFL per scenario              NaN      NaN      NaN
Best StaticNumFL per scenario NAME         NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN
Best Daily Dynamic Policy NAME             NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN
Best Dynamic Policy per scenario NAME      NaN      NaN      NaN

                                      RUSH_HOUR_EXT                    \
                                              av0.1    av0.2    av0.3
NO PTL                                       517.95   520.21  517.565
BUS-ONLY PTL                                523.465  527.125  527.125
Best Daily HOV policy                       485.255  515.675  514.345
Best Daily HOV policy NAME                   Plus_3   Plus_3   Plus_3
Best HOV policy per scenario                    NaN      NaN      NaN
Best HOV policy per scenario NAME               NaN      NaN      NaN
Best Daily StaticNumFL                          NaN      NaN      NaN
Best Daily StaticNumFL NAME                     NaN      NaN      NaN
Best StaticNumFL per scenario                   NaN      NaN      NaN
Best StaticNumFL per scenario NAME              NaN      NaN      NaN
Best Daily Dynamic Policy                       NaN      NaN      NaN
Best Daily Dynamic Policy NAME                  NaN      NaN      NaN
Best Dynamic Policy per scenario                NaN      NaN      NaN
Best Dynamic Policy per scenario NAME           NaN      NaN      NaN

                                                ... Closed_WEEKEND          \
                                         av0.4  ...          av0.3   av0.4
NO PTL                                  517.64  ...          20.06   20.38
BUS-ONLY PTL                            531.82  ...          21.19  21.605
Best Daily HOV policy                  511.655  ...          21.28  21.075
Best Daily HOV policy NAME              Plus_3  ...         Plus_3  Plus_3
Best HOV policy per scenario               NaN  ...            NaN     NaN
Best HOV policy per scenario NAME          NaN  ...            NaN     NaN
Best Daily StaticNumFL                     NaN  ...            NaN     NaN
Best Daily StaticNumFL NAME                NaN  ...            NaN     NaN
Best StaticNumFL per scenario              NaN  ...            NaN     NaN
Best StaticNumFL per scenario NAME         NaN  ...            NaN     NaN
Best Daily Dynamic Policy                  NaN  ...            NaN     NaN
Best Daily Dynamic Policy NAME             NaN  ...            NaN     NaN
Best Dynamic Policy per scenario           NaN  ...            NaN     NaN
Best Dynamic Policy per scenario NAME      NaN  ...            NaN     NaN

                                                       \
                                        av0.6   av0.8
NO PTL                                  19.78   19.98
BUS-ONLY PTL                            20.67   21.18
Best Daily HOV policy                  19.915  20.915
Best Daily HOV policy NAME             Plus_3  Plus_3
Best HOV policy per scenario              NaN     NaN
Best HOV policy per scenario NAME         NaN     NaN
Best Daily StaticNumFL                    NaN     NaN
Best Daily StaticNumFL NAME               NaN     NaN
Best StaticNumFL per scenario             NaN     NaN
Best StaticNumFL per scenario NAME        NaN     NaN
Best Daily Dynamic Policy                 NaN     NaN
Best Daily Dynamic Policy NAME            NaN     NaN
Best Dynamic Policy per scenario          NaN     NaN
Best Dynamic Policy per scenario NAME     NaN     NaN

                                      Closed_MODERATE_RUSH_HOUR           \
                                                          av0.1    av0.2
NO PTL                                                  308.725  307.755
BUS-ONLY PTL                                              286.1   284.25
Best Daily HOV policy                                    272.37  267.515
Best Daily HOV policy NAME                               Plus_3   Plus_3
Best HOV policy per scenario                                NaN      NaN
Best HOV policy per scenario NAME                           NaN      NaN
Best Daily StaticNumFL                                      NaN      NaN
Best Daily StaticNumFL NAME                                 NaN      NaN
Best StaticNumFL per scenario                               NaN      NaN
Best StaticNumFL per scenario NAME                          NaN      NaN
Best Daily Dynamic Policy                                   NaN      NaN
Best Daily Dynamic Policy NAME                              NaN      NaN
Best Dynamic Policy per scenario                            NaN      NaN
Best Dynamic Policy per scenario NAME                       NaN      NaN


                                        av0.3    av0.4    av0.6    av0.8
NO PTL                                 311.81  313.755  310.965  305.155
BUS-ONLY PTL                           288.21   289.69  285.615   289.49
Best Daily HOV policy                  280.08   272.22  262.985   275.95
Best Daily HOV policy NAME             Plus_3   Plus_3   Plus_3   Plus_3
Best HOV policy per scenario              NaN      NaN      NaN      NaN
Best HOV policy per scenario NAME         NaN      NaN      NaN      NaN
Best Daily StaticNumFL                    NaN      NaN      NaN      NaN
Best Daily StaticNumFL NAME               NaN      NaN      NaN      NaN
Best StaticNumFL per scenario             NaN      NaN      NaN      NaN
Best StaticNumFL per scenario NAME        NaN      NaN      NaN      NaN
Best Daily Dynamic Policy                 NaN      NaN      NaN      NaN
Best Daily Dynamic Policy NAME            NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario          NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario NAME     NaN      NaN      NaN      NaN

[14 rows x 66 columns]

# Adding best HOV policy per scenario

In [33]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best HOV policy per scenario",col] = final_LeftCompScenarios[col].loc[HOVs].min()
        final_results.loc["Best HOV policy per scenario NAME",col] = final_LeftCompScenarios[col].loc[HOVs].idxmin()
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best HOV policy per scenario",col] = final_LeftCompDaily[col].loc[HOVs].min()
        final_results.loc["Best HOV policy per scenario NAME",col] = final_LeftCompDaily[col].loc[HOVs].idxmin()
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best HOV policy per scenario",col] = final_ClosedLeftCompScenarios[col].loc[HOVs].min()
        final_results.loc["Best HOV policy per scenario NAME",col] = final_ClosedLeftCompScenarios[col].loc[HOVs].idxmin()

In [34]:
final_results

                                      LeftCompDaily                    \
                                              av0.1    av0.2    av0.3
NO PTL                                      4299.88  4300.38  4306.26
BUS-ONLY PTL                                3959.38  3959.71  3962.75
Best Daily HOV policy                       3523.02  3529.48  3490.59
Best Daily HOV policy NAME                   Plus_3   Plus_3   Plus_3
Best HOV policy per scenario                3523.02  3529.48  3490.59
Best HOV policy per scenario NAME            Plus_3   Plus_3   Plus_3
Best Daily StaticNumFL                          NaN      NaN      NaN
Best Daily StaticNumFL NAME                     NaN      NaN      NaN
Best StaticNumFL per scenario                   NaN      NaN      NaN
Best StaticNumFL per scenario NAME              NaN      NaN      NaN
Best Daily Dynamic Policy                       NaN      NaN      NaN
Best Daily Dynamic Policy NAME                  NaN      NaN      NaN
Best Dynamic Policy per scenario                NaN      NaN      NaN
Best Dynamic Policy per scenario NAME           NaN      NaN      NaN

                                                                  \
                                         av0.4    av0.6    av0.8
NO PTL                                 4306.22  4300.79   4299.4
BUS-ONLY PTL                           3964.21  3961.77  3958.67
Best Daily HOV policy                  3597.59  3636.39  3581.58
Best Daily HOV policy NAME              Plus_3   Plus_3   Plus_3
Best HOV policy per scenario           3597.59  3555.74  3490.04
Best HOV policy per scenario NAME       Plus_3   Plus_4   Plus_4
Best Daily StaticNumFL                     NaN      NaN      NaN
Best Daily StaticNumFL NAME                NaN      NaN      NaN
Best StaticNumFL per scenario              NaN      NaN      NaN
Best StaticNumFL per scenario NAME         NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN
Best Daily Dynamic Policy NAME             NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN
Best Dynamic Policy per scenario NAME      NaN      NaN      NaN

                                      RUSH_HOUR_EXT                    \
                                              av0.1    av0.2    av0.3
NO PTL                                       517.95   520.21  517.565
BUS-ONLY PTL                                523.465  527.125  527.125
Best Daily HOV policy                       485.255  515.675  514.345
Best Daily HOV policy NAME                   Plus_3   Plus_3   Plus_3
Best HOV policy per scenario                485.255  500.865  514.345
Best HOV policy per scenario NAME            Plus_3   Plus_5   Plus_3
Best Daily StaticNumFL                          NaN      NaN      NaN
Best Daily StaticNumFL NAME                     NaN      NaN      NaN
Best StaticNumFL per scenario                   NaN      NaN      NaN
Best StaticNumFL per scenario NAME              NaN      NaN      NaN
Best Daily Dynamic Policy                       NaN      NaN      NaN
Best Daily Dynamic Policy NAME                  NaN      NaN      NaN
Best Dynamic Policy per scenario                NaN      NaN      NaN
Best Dynamic Policy per scenario NAME           NaN      NaN      NaN

                                                ... Closed_WEEKEND          \
                                         av0.4  ...          av0.3   av0.4
NO PTL                                  517.64  ...          20.06   20.38
BUS-ONLY PTL                            531.82  ...          21.19  21.605
Best Daily HOV policy                  511.655  ...          21.28  21.075
Best Daily HOV policy NAME              Plus_3  ...         Plus_3  Plus_3
Best HOV policy per scenario           505.375  ...           19.6   19.08
Best HOV policy per scenario NAME       Plus_5  ...         Plus_2  Plus_2
Best Daily StaticNumFL                     NaN  ...            NaN     NaN
Best Daily StaticNumFL NAME                NaN  ...            NaN     NaN
Best StaticNumFL per scenario              NaN  ...            NaN     NaN
Best StaticNumFL per scenario NAME         NaN  ...            NaN     NaN
Best Daily Dynamic Policy                  NaN  ...            NaN     NaN
Best Daily Dynamic Policy NAME             NaN  ...            NaN     NaN
Best Dynamic Policy per scenario           NaN  ...            NaN     NaN
Best Dynamic Policy per scenario NAME      NaN  ...            NaN     NaN

                                                       \
                                        av0.6   av0.8
NO PTL                                  19.78   19.98
BUS-ONLY PTL                            20.67   21.18
Best Daily HOV policy                  19.915  20.915
Best Daily HOV policy NAME             Plus_3  Plus_3
Best HOV policy per scenario           19.225   19.42
Best HOV policy per scenario NAME      Plus_2  Plus_2
Best Daily StaticNumFL                    NaN     NaN
Best Daily StaticNumFL NAME               NaN     NaN
Best StaticNumFL per scenario             NaN     NaN
Best StaticNumFL per scenario NAME        NaN     NaN
Best Daily Dynamic Policy                 NaN     NaN
Best Daily Dynamic Policy NAME            NaN     NaN
Best Dynamic Policy per scenario          NaN     NaN
Best Dynamic Policy per scenario NAME     NaN     NaN

                                      Closed_MODERATE_RUSH_HOUR           \
                                                          av0.1    av0.2
NO PTL                                                  308.725  307.755
BUS-ONLY PTL                                              286.1   284.25
Best Daily HOV policy                                    272.37  267.515
Best Daily HOV policy NAME                               Plus_3   Plus_3
Best HOV policy per scenario                             272.37  267.325
Best HOV policy per scenario NAME                        Plus_3   Plus_4
Best Daily StaticNumFL                                      NaN      NaN
Best Daily StaticNumFL NAME                                 NaN      NaN
Best StaticNumFL per scenario                               NaN      NaN
Best StaticNumFL per scenario NAME                          NaN      NaN
Best Daily Dynamic Policy                                   NaN      NaN
Best Daily Dynamic Policy NAME                              NaN      NaN
Best Dynamic Policy per scenario                            NaN      NaN
Best Dynamic Policy per scenario NAME                       NaN      NaN


                                        av0.3    av0.4    av0.6    av0.8
NO PTL                                 311.81  313.755  310.965  305.155
BUS-ONLY PTL                           288.21   289.69  285.615   289.49
Best Daily HOV policy                  280.08   272.22  262.985   275.95
Best Daily HOV policy NAME             Plus_3   Plus_3   Plus_3   Plus_3
Best HOV policy per scenario           280.08   270.15  262.985   272.56
Best HOV policy per scenario NAME      Plus_3   Plus_4   Plus_3   Plus_4
Best Daily StaticNumFL                    NaN      NaN      NaN      NaN
Best Daily StaticNumFL NAME               NaN      NaN      NaN      NaN
Best StaticNumFL per scenario             NaN      NaN      NaN      NaN
Best StaticNumFL per scenario NAME        NaN      NaN      NaN      NaN
Best Daily Dynamic Policy                 NaN      NaN      NaN      NaN
Best Daily Dynamic Policy NAME            NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario          NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario NAME     NaN      NaN      NaN      NaN

[14 rows x 66 columns]

# Adding best daily StaticNumFL

In [35]:
StaticNumFLs = [f"StaticNumPassFL_{i}" for i in range(1,6)]
LeftCompDaily_StaticNumFLs =  final_LeftCompDaily.loc[StaticNumFLs]
LeftCompDaily_StaticNumFLs_idx = row_with_max_min_count(LeftCompDaily_StaticNumFLs)
final_results.loc["Best Daily StaticNumFL NAME"] = LeftCompDaily_StaticNumFLs_idx
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Daily StaticNumFL",col] = final_LeftCompScenarios.loc[LeftCompDaily_StaticNumFLs_idx,col]
        
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Daily StaticNumFL",col] = final_LeftCompDaily.loc[LeftCompDaily_StaticNumFLs_idx,col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Daily StaticNumFL",col] = final_ClosedLeftCompScenarios.loc[LeftCompDaily_StaticNumFLs_idx,col]

In [36]:
final_results

                                           LeftCompDaily                     \
                                                   av0.1              av0.2
NO PTL                                           4299.88            4300.38
BUS-ONLY PTL                                     3959.38            3959.71
Best Daily HOV policy                            3523.02            3529.48
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     3523.02            3529.48
Best HOV policy per scenario NAME                 Plus_3             Plus_3
Best Daily StaticNumFL                           3589.44            3644.66
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.3              av0.4
NO PTL                                           4306.26            4306.22
BUS-ONLY PTL                                     3962.75            3964.21
Best Daily HOV policy                            3490.59            3597.59
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     3490.59            3597.59
Best HOV policy per scenario NAME                 Plus_3             Plus_3
Best Daily StaticNumFL                           3486.99            3600.17
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.6              av0.8
NO PTL                                           4300.79             4299.4
BUS-ONLY PTL                                     3961.77            3958.67
Best Daily HOV policy                            3636.39            3581.58
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     3555.74            3490.04
Best HOV policy per scenario NAME                 Plus_4             Plus_4
Best Daily StaticNumFL                            3853.2             4364.4
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                           RUSH_HOUR_EXT                     \
                                                   av0.1              av0.2
NO PTL                                            517.95             520.21
BUS-ONLY PTL                                     523.465            527.125
Best Daily HOV policy                            485.255            515.675
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     485.255            500.865
Best HOV policy per scenario NAME                 Plus_3             Plus_5
Best Daily StaticNumFL                           519.845             501.59
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.3              av0.4
NO PTL                                           517.565             517.64
BUS-ONLY PTL                                     527.125             531.82
Best Daily HOV policy                            514.345            511.655
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     514.345            505.375
Best HOV policy per scenario NAME                 Plus_3             Plus_5
Best Daily StaticNumFL                           525.825            491.355
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                       ...     Closed_WEEKEND  \
                                       ...              av0.3
NO PTL                                 ...              20.06
BUS-ONLY PTL                           ...              21.19
Best Daily HOV policy                  ...              21.28
Best Daily HOV policy NAME             ...             Plus_3
Best HOV policy per scenario           ...               19.6
Best HOV policy per scenario NAME      ...             Plus_2
Best Daily StaticNumFL                 ...               20.6
Best Daily StaticNumFL NAME            ...  StaticNumPassFL_2
Best StaticNumFL per scenario          ...                NaN
Best StaticNumFL per scenario NAME     ...                NaN
Best Daily Dynamic Policy              ...                NaN
Best Daily Dynamic Policy NAME         ...                NaN
Best Dynamic Policy per scenario       ...                NaN
Best Dynamic Policy per scenario NAME  ...                NaN

                                                                             \
                                                   av0.4              av0.6
NO PTL                                             20.38              19.78
BUS-ONLY PTL                                      21.605              20.67
Best Daily HOV policy                             21.075             19.915
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                       19.08             19.225
Best HOV policy per scenario NAME                 Plus_2             Plus_2
Best Daily StaticNumFL                            20.625             19.235
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                          \
                                                   av0.8
NO PTL                                             19.98
BUS-ONLY PTL                                       21.18
Best Daily HOV policy                             20.915
Best Daily HOV policy NAME                        Plus_3
Best HOV policy per scenario                       19.42
Best HOV policy per scenario NAME                 Plus_2
Best Daily StaticNumFL                              19.3
Best Daily StaticNumFL NAME            StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN
Best StaticNumFL per scenario NAME                   NaN
Best Daily Dynamic Policy                            NaN
Best Daily Dynamic Policy NAME                       NaN
Best Dynamic Policy per scenario                     NaN
Best Dynamic Policy per scenario NAME                NaN

                                      Closed_MODERATE_RUSH_HOUR  \
                                                          av0.1
NO PTL                                                  308.725
BUS-ONLY PTL                                              286.1
Best Daily HOV policy                                    272.37
Best Daily HOV policy NAME                               Plus_3
Best HOV policy per scenario                             272.37
Best HOV policy per scenario NAME                        Plus_3
Best Daily StaticNumFL                                  271.885
Best Daily StaticNumFL NAME                   StaticNumPassFL_2
Best StaticNumFL per scenario                               NaN
Best StaticNumFL per scenario NAME                          NaN
Best Daily Dynamic Policy                                   NaN
Best Daily Dynamic Policy NAME                              NaN
Best Dynamic Policy per scenario                            NaN
Best Dynamic Policy per scenario NAME                       NaN

                                                                             \
                                                   av0.2              av0.3
NO PTL                                           307.755             311.81
BUS-ONLY PTL                                      284.25             288.21
Best Daily HOV policy                            267.515             280.08
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     267.325             280.08
Best HOV policy per scenario NAME                 Plus_4             Plus_3
Best Daily StaticNumFL                            269.44             260.22
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.4              av0.6
NO PTL                                           313.755            310.965
BUS-ONLY PTL                                      289.69            285.615
Best Daily HOV policy                             272.22            262.985
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                      270.15            262.985
Best HOV policy per scenario NAME                 Plus_4             Plus_3
Best Daily StaticNumFL                           266.325             299.09
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN                NaN
Best StaticNumFL per scenario NAME                   NaN                NaN
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN


                                                   av0.8
NO PTL                                           305.155
BUS-ONLY PTL                                      289.49
Best Daily HOV policy                             275.95
Best Daily HOV policy NAME                        Plus_3
Best HOV policy per scenario                      272.56
Best HOV policy per scenario NAME                 Plus_4
Best Daily StaticNumFL                            332.73
Best Daily StaticNumFL NAME            StaticNumPassFL_2
Best StaticNumFL per scenario                        NaN
Best StaticNumFL per scenario NAME                   NaN
Best Daily Dynamic Policy                            NaN
Best Daily Dynamic Policy NAME                       NaN
Best Dynamic Policy per scenario                     NaN
Best Dynamic Policy per scenario NAME                NaN

[14 rows x 66 columns]

# Adding best StaticNumFL per scenario

In [37]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best StaticNumFL per scenario",col] = final_LeftCompScenarios[col].loc[StaticNumFLs].min()
        final_results.loc["Best StaticNumFL per scenario NAME",col] = final_LeftCompScenarios[col].loc[StaticNumFLs].idxmin()
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best StaticNumFL per scenario",col] = final_LeftCompDaily[col].loc[StaticNumFLs].min()
        final_results.loc["Best StaticNumFL per scenario NAME",col] = final_LeftCompDaily[col].loc[StaticNumFLs].idxmin()
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best StaticNumFL per scenario",col] = final_ClosedLeftCompScenarios[col].loc[StaticNumFLs].min()
        final_results.loc["Best StaticNumFL per scenario NAME",col] = final_ClosedLeftCompScenarios[col].loc[StaticNumFLs].idxmin()

In [38]:
final_results

                                           LeftCompDaily                     \
                                                   av0.1              av0.2
NO PTL                                           4299.88            4300.38
BUS-ONLY PTL                                     3959.38            3959.71
Best Daily HOV policy                            3523.02            3529.48
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     3523.02            3529.48
Best HOV policy per scenario NAME                 Plus_3             Plus_3
Best Daily StaticNumFL                           3589.44            3644.66
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                    3589.44            3644.66
Best StaticNumFL per scenario NAME     StaticNumPassFL_2  StaticNumPassFL_2
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.3              av0.4
NO PTL                                           4306.26            4306.22
BUS-ONLY PTL                                     3962.75            3964.21
Best Daily HOV policy                            3490.59            3597.59
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     3490.59            3597.59
Best HOV policy per scenario NAME                 Plus_3             Plus_3
Best Daily StaticNumFL                           3486.99            3600.17
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                    3486.99            3600.17
Best StaticNumFL per scenario NAME     StaticNumPassFL_2  StaticNumPassFL_2
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.6              av0.8
NO PTL                                           4300.79             4299.4
BUS-ONLY PTL                                     3961.77            3958.67
Best Daily HOV policy                            3636.39            3581.58
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     3555.74            3490.04
Best HOV policy per scenario NAME                 Plus_4             Plus_4
Best Daily StaticNumFL                            3853.2             4364.4
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                    3488.79            3570.62
Best StaticNumFL per scenario NAME     StaticNumPassFL_3  StaticNumPassFL_3
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                           RUSH_HOUR_EXT                     \
                                                   av0.1              av0.2
NO PTL                                            517.95             520.21
BUS-ONLY PTL                                     523.465            527.125
Best Daily HOV policy                            485.255            515.675
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     485.255            500.865
Best HOV policy per scenario NAME                 Plus_3             Plus_5
Best Daily StaticNumFL                           519.845             501.59
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                     489.46            494.595
Best StaticNumFL per scenario NAME     StaticNumPassFL_1  StaticNumPassFL_1
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.3              av0.4
NO PTL                                           517.565             517.64
BUS-ONLY PTL                                     527.125             531.82
Best Daily HOV policy                            514.345            511.655
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     514.345            505.375
Best HOV policy per scenario NAME                 Plus_3             Plus_5
Best Daily StaticNumFL                           525.825            491.355
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                     485.36            491.355
Best StaticNumFL per scenario NAME     StaticNumPassFL_3  StaticNumPassFL_2
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                       ...     Closed_WEEKEND  \
                                       ...              av0.3
NO PTL                                 ...              20.06
BUS-ONLY PTL                           ...              21.19
Best Daily HOV policy                  ...              21.28
Best Daily HOV policy NAME             ...             Plus_3
Best HOV policy per scenario           ...               19.6
Best HOV policy per scenario NAME      ...             Plus_2
Best Daily StaticNumFL                 ...               20.6
Best Daily StaticNumFL NAME            ...  StaticNumPassFL_2
Best StaticNumFL per scenario          ...              19.96
Best StaticNumFL per scenario NAME     ...  StaticNumPassFL_1
Best Daily Dynamic Policy              ...                NaN
Best Daily Dynamic Policy NAME         ...                NaN
Best Dynamic Policy per scenario       ...                NaN
Best Dynamic Policy per scenario NAME  ...                NaN

                                                                             \
                                                   av0.4              av0.6
NO PTL                                             20.38              19.78
BUS-ONLY PTL                                      21.605              20.67
Best Daily HOV policy                             21.075             19.915
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                       19.08             19.225
Best HOV policy per scenario NAME                 Plus_2             Plus_2
Best Daily StaticNumFL                            20.625             19.235
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                     19.255             19.055
Best StaticNumFL per scenario NAME     StaticNumPassFL_1  StaticNumPassFL_1
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                          \
                                                   av0.8
NO PTL                                             19.98
BUS-ONLY PTL                                       21.18
Best Daily HOV policy                             20.915
Best Daily HOV policy NAME                        Plus_3
Best HOV policy per scenario                       19.42
Best HOV policy per scenario NAME                 Plus_2
Best Daily StaticNumFL                              19.3
Best Daily StaticNumFL NAME            StaticNumPassFL_2
Best StaticNumFL per scenario                     19.065
Best StaticNumFL per scenario NAME     StaticNumPassFL_1
Best Daily Dynamic Policy                            NaN
Best Daily Dynamic Policy NAME                       NaN
Best Dynamic Policy per scenario                     NaN
Best Dynamic Policy per scenario NAME                NaN

                                      Closed_MODERATE_RUSH_HOUR  \
                                                          av0.1
NO PTL                                                  308.725
BUS-ONLY PTL                                              286.1
Best Daily HOV policy                                    272.37
Best Daily HOV policy NAME                               Plus_3
Best HOV policy per scenario                             272.37
Best HOV policy per scenario NAME                        Plus_3
Best Daily StaticNumFL                                  271.885
Best Daily StaticNumFL NAME                   StaticNumPassFL_2
Best StaticNumFL per scenario                            269.08
Best StaticNumFL per scenario NAME            StaticNumPassFL_1
Best Daily Dynamic Policy                                   NaN
Best Daily Dynamic Policy NAME                              NaN
Best Dynamic Policy per scenario                            NaN
Best Dynamic Policy per scenario NAME                       NaN

                                                                             \
                                                   av0.2              av0.3
NO PTL                                           307.755             311.81
BUS-ONLY PTL                                      284.25             288.21
Best Daily HOV policy                            267.515             280.08
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                     267.325             280.08
Best HOV policy per scenario NAME                 Plus_4             Plus_3
Best Daily StaticNumFL                            269.44             260.22
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                     269.44             260.22
Best StaticNumFL per scenario NAME     StaticNumPassFL_2  StaticNumPassFL_2
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN

                                                                             \
                                                   av0.4              av0.6
NO PTL                                           313.755            310.965
BUS-ONLY PTL                                      289.69            285.615
Best Daily HOV policy                             272.22            262.985
Best Daily HOV policy NAME                        Plus_3             Plus_3
Best HOV policy per scenario                      270.15            262.985
Best HOV policy per scenario NAME                 Plus_4             Plus_3
Best Daily StaticNumFL                           266.325             299.09
Best Daily StaticNumFL NAME            StaticNumPassFL_2  StaticNumPassFL_2
Best StaticNumFL per scenario                    266.325            272.665
Best StaticNumFL per scenario NAME     StaticNumPassFL_2  StaticNumPassFL_3
Best Daily Dynamic Policy                            NaN                NaN
Best Daily Dynamic Policy NAME                       NaN                NaN
Best Dynamic Policy per scenario                     NaN                NaN
Best Dynamic Policy per scenario NAME                NaN                NaN


                                                   av0.8
NO PTL                                           305.155
BUS-ONLY PTL                                      289.49
Best Daily HOV policy                             275.95
Best Daily HOV policy NAME                        Plus_3
Best HOV policy per scenario                      272.56
Best HOV policy per scenario NAME                 Plus_4
Best Daily StaticNumFL                            332.73
Best Daily StaticNumFL NAME            StaticNumPassFL_2
Best StaticNumFL per scenario                     249.16
Best StaticNumFL per scenario NAME     StaticNumPassFL_3
Best Daily Dynamic Policy                            NaN
Best Daily Dynamic Policy NAME                       NaN
Best Dynamic Policy per scenario                     NaN
Best Dynamic Policy per scenario NAME                NaN

[14 rows x 66 columns]

# Adding best daily Dynamic Policy

In [39]:
DynamicPolicies = list(set(final_LeftCompScenarios.index.tolist())-set(HOVs+StaticNumFLs+["Nothing"]))
LeftCompDaily_DynamicPolicies =  final_LeftCompDaily.loc[DynamicPolicies]
LeftCompDaily_DynamicPolicies_idx = row_with_max_min_count(LeftCompDaily_DynamicPolicies)
final_results.loc["Best Daily Dynamic Policy NAME"] = LeftCompDaily_DynamicPolicies_idx
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Daily Dynamic Policy",col] = final_LeftCompScenarios.loc[LeftCompDaily_DynamicPolicies_idx,col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Daily Dynamic Policy",col] = final_LeftCompDaily.loc[LeftCompDaily_DynamicPolicies_idx,col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Daily Dynamic Policy",col] = final_ClosedLeftCompScenarios.loc[LeftCompDaily_DynamicPolicies_idx,col]

In [40]:
final_results

                                              LeftCompDaily  \
                                                      av0.1
NO PTL                                              4299.88
BUS-ONLY PTL                                        3959.38
Best Daily HOV policy                               3523.02
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3523.02
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3589.44
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3589.44
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3676.56
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.2
NO PTL                                              4300.38
BUS-ONLY PTL                                        3959.71
Best Daily HOV policy                               3529.48
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3529.48
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3644.66
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3644.66
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3621.85
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.3
NO PTL                                              4306.26
BUS-ONLY PTL                                        3962.75
Best Daily HOV policy                               3490.59
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3490.59
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3486.99
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3486.99
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3554.58
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.4
NO PTL                                              4306.22
BUS-ONLY PTL                                        3964.21
Best Daily HOV policy                               3597.59
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3597.59
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3600.17
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3600.17
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3679.79
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.6
NO PTL                                              4300.79
BUS-ONLY PTL                                        3961.77
Best Daily HOV policy                               3636.39
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3555.74
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               3853.2
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3488.79
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           3558.54
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.8
NO PTL                                               4299.4
BUS-ONLY PTL                                        3958.67
Best Daily HOV policy                               3581.58
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3490.04
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               4364.4
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3570.62
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           3458.81
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                              RUSH_HOUR_EXT  \
                                                      av0.1
NO PTL                                               517.95
BUS-ONLY PTL                                        523.465
Best Daily HOV policy                               485.255
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        485.255
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              519.845
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        489.46
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                           503.065
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.2
NO PTL                                               520.21
BUS-ONLY PTL                                        527.125
Best Daily HOV policy                               515.675
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        500.865
Best HOV policy per scenario NAME                    Plus_5
Best Daily StaticNumFL                               501.59
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       494.595
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                           523.535
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.3
NO PTL                                              517.565
BUS-ONLY PTL                                        527.125
Best Daily HOV policy                               514.345
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        514.345
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              525.825
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        485.36
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           538.735
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             ...  \
                                                      av0.4  ...
NO PTL                                               517.64  ...
BUS-ONLY PTL                                         531.82  ...
Best Daily HOV policy                               511.655  ...
Best Daily HOV policy NAME                           Plus_3  ...
Best HOV policy per scenario                        505.375  ...
Best HOV policy per scenario NAME                    Plus_5  ...
Best Daily StaticNumFL                              491.355  ...
Best Daily StaticNumFL NAME               StaticNumPassFL_2  ...
Best StaticNumFL per scenario                       491.355  ...
Best StaticNumFL per scenario NAME        StaticNumPassFL_2  ...
Best Daily Dynamic Policy                           507.155  ...
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat  ...
Best Dynamic Policy per scenario                        NaN  ...
Best Dynamic Policy per scenario NAME                   NaN  ...

                                             Closed_WEEKEND  \
                                                      av0.3
NO PTL                                                20.06
BUS-ONLY PTL                                          21.19
Best Daily HOV policy                                 21.28
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                           19.6
Best HOV policy per scenario NAME                    Plus_2
Best Daily StaticNumFL                                 20.6
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                         19.96
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                             21.17
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.4
NO PTL                                                20.38
BUS-ONLY PTL                                         21.605
Best Daily HOV policy                                21.075
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                          19.08
Best HOV policy per scenario NAME                    Plus_2
Best Daily StaticNumFL                               20.625
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        19.255
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                            21.665
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.6
NO PTL                                                19.78
BUS-ONLY PTL                                          20.67
Best Daily HOV policy                                19.915
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                         19.225
Best HOV policy per scenario NAME                    Plus_2
Best Daily StaticNumFL                               19.235
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        19.055
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                             20.67
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.8
NO PTL                                                19.98
BUS-ONLY PTL                                          21.18
Best Daily HOV policy                                20.915
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                          19.42
Best HOV policy per scenario NAME                    Plus_2
Best Daily StaticNumFL                                 19.3
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        19.065
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                             20.09
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                      Closed_MODERATE_RUSH_HOUR  \
                                                          av0.1
NO PTL                                                  308.725
BUS-ONLY PTL                                              286.1
Best Daily HOV policy                                    272.37
Best Daily HOV policy NAME                               Plus_3
Best HOV policy per scenario                             272.37
Best HOV policy per scenario NAME                        Plus_3
Best Daily StaticNumFL                                  271.885
Best Daily StaticNumFL NAME                   StaticNumPassFL_2
Best StaticNumFL per scenario                            269.08
Best StaticNumFL per scenario NAME            StaticNumPassFL_1
Best Daily Dynamic Policy                                306.03
Best Daily Dynamic Policy NAME             Trained_TreesSimFeat
Best Dynamic Policy per scenario                            NaN
Best Dynamic Policy per scenario NAME                       NaN

                                                             \
                                                      av0.2
NO PTL                                              307.755
BUS-ONLY PTL                                         284.25
Best Daily HOV policy                               267.515
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        267.325
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               269.44
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        269.44
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                            281.89
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.3
NO PTL                                               311.81
BUS-ONLY PTL                                         288.21
Best Daily HOV policy                                280.08
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                         280.08
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                               260.22
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        260.22
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                            290.83
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.4
NO PTL                                              313.755
BUS-ONLY PTL                                         289.69
Best Daily HOV policy                                272.22
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                         270.15
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                              266.325
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       266.325
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                            282.01
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

                                                             \
                                                      av0.6
NO PTL                                              310.965
BUS-ONLY PTL                                        285.615
Best Daily HOV policy                               262.985
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        262.985
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                               299.09
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       272.665
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                            273.23
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN


                                                      av0.8
NO PTL                                              305.155
BUS-ONLY PTL                                         289.49
Best Daily HOV policy                                275.95
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                         272.56
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               332.73
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        249.16
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           283.465
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                        NaN
Best Dynamic Policy per scenario NAME                   NaN

[14 rows x 66 columns]

# Adding best Dynamic Policy per scenario

In [41]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Dynamic Policy per scenario",col] = final_LeftCompScenarios[col].loc[DynamicPolicies].min()
        final_results.loc["Best Dynamic Policy per scenario NAME",col] = final_LeftCompScenarios[col].loc[DynamicPolicies].idxmin()
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Dynamic Policy per scenario",col] = final_LeftCompDaily[col].loc[DynamicPolicies].min()
        final_results.loc["Best Dynamic Policy per scenario NAME",col] = final_LeftCompDaily[col].loc[DynamicPolicies].idxmin()
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Dynamic Policy per scenario",col] = final_ClosedLeftCompScenarios[col].loc[DynamicPolicies].min()
        final_results.loc["Best Dynamic Policy per scenario NAME",col] = final_ClosedLeftCompScenarios[col].loc[DynamicPolicies].idxmin()

In [42]:
final_results

                                                                LeftCompDaily  \
                                                                        av0.1
NO PTL                                                                4299.88
BUS-ONLY PTL                                                          3959.38
Best Daily HOV policy                                                 3523.02
Best Daily HOV policy NAME                                             Plus_3
Best HOV policy per scenario                                          3523.02
Best HOV policy per scenario NAME                                      Plus_3
Best Daily StaticNumFL                                                3589.44
Best Daily StaticNumFL NAME                                 StaticNumPassFL_2
Best StaticNumFL per scenario                                         3589.44
Best StaticNumFL per scenario NAME                          StaticNumPassFL_2
Best Daily Dynamic Policy                                             3676.56
Best Daily Dynamic Policy NAME                           Trained_TreesSimFeat
Best Dynamic Policy per scenario                                      3524.88
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_PTL 12 20

                                                             \
                                                      av0.2
NO PTL                                              4300.38
BUS-ONLY PTL                                        3959.71
Best Daily HOV policy                               3529.48
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3529.48
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3644.66
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3644.66
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3621.85
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3621.85
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.3
NO PTL                                              4306.26
BUS-ONLY PTL                                        3962.75
Best Daily HOV policy                               3490.59
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3490.59
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3486.99
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3486.99
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3554.58
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3554.58
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.4
NO PTL                                              4306.22
BUS-ONLY PTL                                        3964.21
Best Daily HOV policy                               3597.59
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3597.59
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3600.17
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3600.17
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3679.79
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3679.79
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.6
NO PTL                                              4300.79
BUS-ONLY PTL                                        3961.77
Best Daily HOV policy                               3636.39
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3555.74
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               3853.2
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3488.79
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           3558.54
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3558.54
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.8
NO PTL                                               4299.4
BUS-ONLY PTL                                        3958.67
Best Daily HOV policy                               3581.58
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3490.04
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               4364.4
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3570.62
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           3458.81
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3458.81
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                                    RUSH_HOUR_EXT  \
                                                                            av0.1
NO PTL                                                                     517.95
BUS-ONLY PTL                                                              523.465
Best Daily HOV policy                                                     485.255
Best Daily HOV policy NAME                                                 Plus_3
Best HOV policy per scenario                                              485.255
Best HOV policy per scenario NAME                                          Plus_3
Best Daily StaticNumFL                                                    519.845
Best Daily StaticNumFL NAME                                     StaticNumPassFL_2
Best StaticNumFL per scenario                                              489.46
Best StaticNumFL per scenario NAME                              StaticNumPassFL_1
Best Daily Dynamic Policy                                                 503.065
Best Daily Dynamic Policy NAME                               Trained_TreesSimFeat
Best Dynamic Policy per scenario                                          488.875
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_end_PTL 16 22

                                                             \
                                                      av0.2
NO PTL                                               520.21
BUS-ONLY PTL                                        527.125
Best Daily HOV policy                               515.675
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        500.865
Best HOV policy per scenario NAME                    Plus_5
Best Daily StaticNumFL                               501.59
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       494.595
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                           523.535
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                     488.69
Best Dynamic Policy per scenario NAME     Trained_RFSimFeat

                                                             \
                                                      av0.3
NO PTL                                              517.565
BUS-ONLY PTL                                        527.125
Best Daily HOV policy                               514.345
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        514.345
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              525.825
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        485.36
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           538.735
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    508.185
Best Dynamic Policy per scenario NAME            Trained_LR

                                                                      ...  \
                                                               av0.4  ...
NO PTL                                                        517.64  ...
BUS-ONLY PTL                                                  531.82  ...
Best Daily HOV policy                                        511.655  ...
Best Daily HOV policy NAME                                    Plus_3  ...
Best HOV policy per scenario                                 505.375  ...
Best HOV policy per scenario NAME                             Plus_5  ...
Best Daily StaticNumFL                                       491.355  ...
Best Daily StaticNumFL NAME                        StaticNumPassFL_2  ...
Best StaticNumFL per scenario                                491.355  ...
Best StaticNumFL per scenario NAME                 StaticNumPassFL_2  ...
Best Daily Dynamic Policy                                    507.155  ...
Best Daily Dynamic Policy NAME                  Trained_TreesSimFeat  ...
Best Dynamic Policy per scenario                             499.145  ...
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeatUnbounded  ...

                                                                   Closed_WEEKEND  \
                                                                            av0.3
NO PTL                                                                      20.06
BUS-ONLY PTL                                                                21.19
Best Daily HOV policy                                                       21.28
Best Daily HOV policy NAME                                                 Plus_3
Best HOV policy per scenario                                                 19.6
Best HOV policy per scenario NAME                                          Plus_2
Best Daily StaticNumFL                                                       20.6
Best Daily StaticNumFL NAME                                     StaticNumPassFL_2
Best StaticNumFL per scenario                                               19.96
Best StaticNumFL per scenario NAME                              StaticNumPassFL_1
Best Daily Dynamic Policy                                                   21.17
Best Daily Dynamic Policy NAME                               Trained_TreesSimFeat
Best Dynamic Policy per scenario                                            18.45
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_end_PTL 16 20

                                                                            \
                                                                     av0.4
NO PTL                                                               20.38
BUS-ONLY PTL                                                        21.605
Best Daily HOV policy                                               21.075
Best Daily HOV policy NAME                                          Plus_3
Best HOV policy per scenario                                         19.08
Best HOV policy per scenario NAME                                   Plus_2
Best Daily StaticNumFL                                              20.625
Best Daily StaticNumFL NAME                              StaticNumPassFL_2
Best StaticNumFL per scenario                                       19.255
Best StaticNumFL per scenario NAME                       StaticNumPassFL_1
Best Daily Dynamic Policy                                           21.665
Best Daily Dynamic Policy NAME                        Trained_TreesSimFeat
Best Dynamic Policy per scenario                                    18.435
Best Dynamic Policy per scenario NAME  Control mean_speed_in_end_PTL 10 20

                                                                            \
                                                                     av0.6
NO PTL                                                               19.78
BUS-ONLY PTL                                                         20.67
Best Daily HOV policy                                               19.915
Best Daily HOV policy NAME                                          Plus_3
Best HOV policy per scenario                                        19.225
Best HOV policy per scenario NAME                                   Plus_2
Best Daily StaticNumFL                                              19.235
Best Daily StaticNumFL NAME                              StaticNumPassFL_2
Best StaticNumFL per scenario                                       19.055
Best StaticNumFL per scenario NAME                       StaticNumPassFL_1
Best Daily Dynamic Policy                                            20.67
Best Daily Dynamic Policy NAME                        Trained_TreesSimFeat
Best Dynamic Policy per scenario                                     17.68
Best Dynamic Policy per scenario NAME  Control mean_speed_in_end_PTL 10 18

                                                                               \
                                                                        av0.8
NO PTL                                                                  19.98
BUS-ONLY PTL                                                            21.18
Best Daily HOV policy                                                  20.915
Best Daily HOV policy NAME                                             Plus_3
Best HOV policy per scenario                                            19.42
Best HOV policy per scenario NAME                                      Plus_2
Best Daily StaticNumFL                                                   19.3
Best Daily StaticNumFL NAME                                 StaticNumPassFL_2
Best StaticNumFL per scenario                                          19.065
Best StaticNumFL per scenario NAME                          StaticNumPassFL_1
Best Daily Dynamic Policy                                               20.09
Best Daily Dynamic Policy NAME                           Trained_TreesSimFeat
Best Dynamic Policy per scenario                                       18.135
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_PTL 16 20

                                           Closed_MODERATE_RUSH_HOUR  \
                                                               av0.1
NO PTL                                                       308.725
BUS-ONLY PTL                                                   286.1
Best Daily HOV policy                                         272.37
Best Daily HOV policy NAME                                    Plus_3
Best HOV policy per scenario                                  272.37
Best HOV policy per scenario NAME                             Plus_3
Best Daily StaticNumFL                                       271.885
Best Daily StaticNumFL NAME                        StaticNumPassFL_2
Best StaticNumFL per scenario                                 269.08
Best StaticNumFL per scenario NAME                 StaticNumPassFL_1
Best Daily Dynamic Policy                                     306.03
Best Daily Dynamic Policy NAME                  Trained_TreesSimFeat
Best Dynamic Policy per scenario                             258.225
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeatUnbounded

                                                                                   \
                                                                            av0.2
NO PTL                                                                    307.755
BUS-ONLY PTL                                                               284.25
Best Daily HOV policy                                                     267.515
Best Daily HOV policy NAME                                                 Plus_3
Best HOV policy per scenario                                              267.325
Best HOV policy per scenario NAME                                          Plus_4
Best Daily StaticNumFL                                                     269.44
Best Daily StaticNumFL NAME                                     StaticNumPassFL_2
Best StaticNumFL per scenario                                              269.44
Best StaticNumFL per scenario NAME                              StaticNumPassFL_2
Best Daily Dynamic Policy                                                  281.89
Best Daily Dynamic Policy NAME                               Trained_TreesSimFeat
Best Dynamic Policy per scenario                                           253.35
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_end_PTL 13 20

                                                                    \
                                                             av0.3
NO PTL                                                      311.81
BUS-ONLY PTL                                                288.21
Best Daily HOV policy                                       280.08
Best Daily HOV policy NAME                                  Plus_3
Best HOV policy per scenario                                280.08
Best HOV policy per scenario NAME                           Plus_3
Best Daily StaticNumFL                                      260.22
Best Daily StaticNumFL NAME                      StaticNumPassFL_2
Best StaticNumFL per scenario                               260.22
Best StaticNumFL per scenario NAME               StaticNumPassFL_2
Best Daily Dynamic Policy                                   290.83
Best Daily Dynamic Policy NAME                Trained_TreesSimFeat
Best Dynamic Policy per scenario                            277.56
Best Dynamic Policy per scenario NAME  Trained_MLPRegressorSimFeat

                                                                      \
                                                               av0.4
NO PTL                                                       313.755
BUS-ONLY PTL                                                  289.69
Best Daily HOV policy                                         272.22
Best Daily HOV policy NAME                                    Plus_3
Best HOV policy per scenario                                  270.15
Best HOV policy per scenario NAME                             Plus_4
Best Daily StaticNumFL                                       266.325
Best Daily StaticNumFL NAME                        StaticNumPassFL_2
Best StaticNumFL per scenario                                266.325
Best StaticNumFL per scenario NAME                 StaticNumPassFL_2
Best Daily Dynamic Policy                                     282.01
Best Daily Dynamic Policy NAME                  Trained_TreesSimFeat

In [47]:
# Highlight the min in each row
def highlight_min(s):
    # filter out indices that contain HOV
    s_without = s[~s.index.str.contains("HOV")]
    is_min = s == min([v for v in s if isinstance(v, (int, float))])
    is_min_without = s == min([v for v in s_without if isinstance(v, (int, float))])
    styles = []
    # set to bold and yellow if it is the min
    for v,u in zip(is_min, is_min_without):
        style = ''
        if v and u:
            style = 'background-color: yellow; font-weight: bold'
        elif v:
            style = 'background-color: yellow'
        elif u:
            style = 'font-weight: bold' 
        styles.append(style)
    return styles
final_results.style.apply(highlight_min, axis=0).to_excel("final_results.xlsx")

In [48]:
final_results

                                                                LeftCompDaily  \
                                                                        av0.1
NO PTL                                                                4299.88
BUS-ONLY PTL                                                          3959.38
Best Daily HOV policy                                                 3523.02
Best Daily HOV policy NAME                                             Plus_3
Best HOV policy per scenario                                          3523.02
Best HOV policy per scenario NAME                                      Plus_3
Best Daily StaticNumFL                                                3589.44
Best Daily StaticNumFL NAME                                 StaticNumPassFL_2
Best StaticNumFL per scenario                                         3589.44
Best StaticNumFL per scenario NAME                          StaticNumPassFL_2
Best Daily Dynamic Policy                                             3676.56
Best Daily Dynamic Policy NAME                           Trained_TreesSimFeat
Best Dynamic Policy per scenario                                      3524.88
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_PTL 12 20

                                                             \
                                                      av0.2
NO PTL                                              4300.38
BUS-ONLY PTL                                        3959.71
Best Daily HOV policy                               3529.48
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3529.48
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3644.66
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3644.66
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3621.85
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3621.85
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.3
NO PTL                                              4306.26
BUS-ONLY PTL                                        3962.75
Best Daily HOV policy                               3490.59
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3490.59
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3486.99
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3486.99
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3554.58
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3554.58
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.4
NO PTL                                              4306.22
BUS-ONLY PTL                                        3964.21
Best Daily HOV policy                               3597.59
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3597.59
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              3600.17
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3600.17
Best StaticNumFL per scenario NAME        StaticNumPassFL_2
Best Daily Dynamic Policy                           3679.79
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3679.79
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.6
NO PTL                                              4300.79
BUS-ONLY PTL                                        3961.77
Best Daily HOV policy                               3636.39
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3555.74
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               3853.2
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3488.79
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           3558.54
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3558.54
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                             \
                                                      av0.8
NO PTL                                               4299.4
BUS-ONLY PTL                                        3958.67
Best Daily HOV policy                               3581.58
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        3490.04
Best HOV policy per scenario NAME                    Plus_4
Best Daily StaticNumFL                               4364.4
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       3570.62
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           3458.81
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    3458.81
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeat

                                                                    RUSH_HOUR_EXT  \
                                                                            av0.1
NO PTL                                                                     517.95
BUS-ONLY PTL                                                              523.465
Best Daily HOV policy                                                     485.255
Best Daily HOV policy NAME                                                 Plus_3
Best HOV policy per scenario                                              485.255
Best HOV policy per scenario NAME                                          Plus_3
Best Daily StaticNumFL                                                    519.845
Best Daily StaticNumFL NAME                                     StaticNumPassFL_2
Best StaticNumFL per scenario                                              489.46
Best StaticNumFL per scenario NAME                              StaticNumPassFL_1
Best Daily Dynamic Policy                                                 503.065
Best Daily Dynamic Policy NAME                               Trained_TreesSimFeat
Best Dynamic Policy per scenario                                          488.875
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_end_PTL 16 22

                                                             \
                                                      av0.2
NO PTL                                               520.21
BUS-ONLY PTL                                        527.125
Best Daily HOV policy                               515.675
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        500.865
Best HOV policy per scenario NAME                    Plus_5
Best Daily StaticNumFL                               501.59
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                       494.595
Best StaticNumFL per scenario NAME        StaticNumPassFL_1
Best Daily Dynamic Policy                           523.535
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                     488.69
Best Dynamic Policy per scenario NAME     Trained_RFSimFeat

                                                             \
                                                      av0.3
NO PTL                                              517.565
BUS-ONLY PTL                                        527.125
Best Daily HOV policy                               514.345
Best Daily HOV policy NAME                           Plus_3
Best HOV policy per scenario                        514.345
Best HOV policy per scenario NAME                    Plus_3
Best Daily StaticNumFL                              525.825
Best Daily StaticNumFL NAME               StaticNumPassFL_2
Best StaticNumFL per scenario                        485.36
Best StaticNumFL per scenario NAME        StaticNumPassFL_3
Best Daily Dynamic Policy                           538.735
Best Daily Dynamic Policy NAME         Trained_TreesSimFeat
Best Dynamic Policy per scenario                    508.185
Best Dynamic Policy per scenario NAME            Trained_LR

                                                                      ...  \
                                                               av0.4  ...
NO PTL                                                        517.64  ...
BUS-ONLY PTL                                                  531.82  ...
Best Daily HOV policy                                        511.655  ...
Best Daily HOV policy NAME                                    Plus_3  ...
Best HOV policy per scenario                                 505.375  ...
Best HOV policy per scenario NAME                             Plus_5  ...
Best Daily StaticNumFL                                       491.355  ...
Best Daily StaticNumFL NAME                        StaticNumPassFL_2  ...
Best StaticNumFL per scenario                                491.355  ...
Best StaticNumFL per scenario NAME                 StaticNumPassFL_2  ...
Best Daily Dynamic Policy                                    507.155  ...
Best Daily Dynamic Policy NAME                  Trained_TreesSimFeat  ...
Best Dynamic Policy per scenario                             499.145  ...
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeatUnbounded  ...

                                                                   Closed_WEEKEND  \
                                                                            av0.3
NO PTL                                                                      20.06
BUS-ONLY PTL                                                                21.19
Best Daily HOV policy                                                       21.28
Best Daily HOV policy NAME                                                 Plus_3
Best HOV policy per scenario                                                 19.6
Best HOV policy per scenario NAME                                          Plus_2
Best Daily StaticNumFL                                                       20.6
Best Daily StaticNumFL NAME                                     StaticNumPassFL_2
Best StaticNumFL per scenario                                               19.96
Best StaticNumFL per scenario NAME                              StaticNumPassFL_1
Best Daily Dynamic Policy                                                   21.17
Best Daily Dynamic Policy NAME                               Trained_TreesSimFeat
Best Dynamic Policy per scenario                                            18.45
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_end_PTL 16 20

                                                                            \
                                                                     av0.4
NO PTL                                                               20.38
BUS-ONLY PTL                                                        21.605
Best Daily HOV policy                                               21.075
Best Daily HOV policy NAME                                          Plus_3
Best HOV policy per scenario                                         19.08
Best HOV policy per scenario NAME                                   Plus_2
Best Daily StaticNumFL                                              20.625
Best Daily StaticNumFL NAME                              StaticNumPassFL_2
Best StaticNumFL per scenario                                       19.255
Best StaticNumFL per scenario NAME                       StaticNumPassFL_1
Best Daily Dynamic Policy                                           21.665
Best Daily Dynamic Policy NAME                        Trained_TreesSimFeat
Best Dynamic Policy per scenario                                    18.435
Best Dynamic Policy per scenario NAME  Control mean_speed_in_end_PTL 10 20

                                                                            \
                                                                     av0.6
NO PTL                                                               19.78
BUS-ONLY PTL                                                         20.67
Best Daily HOV policy                                               19.915
Best Daily HOV policy NAME                                          Plus_3
Best HOV policy per scenario                                        19.225
Best HOV policy per scenario NAME                                   Plus_2
Best Daily StaticNumFL                                              19.235
Best Daily StaticNumFL NAME                              StaticNumPassFL_2
Best StaticNumFL per scenario                                       19.055
Best StaticNumFL per scenario NAME                       StaticNumPassFL_1
Best Daily Dynamic Policy                                            20.67
Best Daily Dynamic Policy NAME                        Trained_TreesSimFeat
Best Dynamic Policy per scenario                                     17.68
Best Dynamic Policy per scenario NAME  Control mean_speed_in_end_PTL 10 18

                                                                               \
                                                                        av0.8
NO PTL                                                                  19.98
BUS-ONLY PTL                                                            21.18
Best Daily HOV policy                                                  20.915
Best Daily HOV policy NAME                                             Plus_3
Best HOV policy per scenario                                            19.42
Best HOV policy per scenario NAME                                      Plus_2
Best Daily StaticNumFL                                                   19.3
Best Daily StaticNumFL NAME                                 StaticNumPassFL_2
Best StaticNumFL per scenario                                          19.065
Best StaticNumFL per scenario NAME                          StaticNumPassFL_1
Best Daily Dynamic Policy                                               20.09
Best Daily Dynamic Policy NAME                           Trained_TreesSimFeat
Best Dynamic Policy per scenario                                       18.135
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_PTL 16 20

                                           Closed_MODERATE_RUSH_HOUR  \
                                                               av0.1
NO PTL                                                       308.725
BUS-ONLY PTL                                                   286.1
Best Daily HOV policy                                         272.37
Best Daily HOV policy NAME                                    Plus_3
Best HOV policy per scenario                                  272.37
Best HOV policy per scenario NAME                             Plus_3
Best Daily StaticNumFL                                       271.885
Best Daily StaticNumFL NAME                        StaticNumPassFL_2
Best StaticNumFL per scenario                                 269.08
Best StaticNumFL per scenario NAME                 StaticNumPassFL_1
Best Daily Dynamic Policy                                     306.03
Best Daily Dynamic Policy NAME                  Trained_TreesSimFeat
Best Dynamic Policy per scenario                             258.225
Best Dynamic Policy per scenario NAME  Trained_TreesSimFeatUnbounded

                                                                                   \
                                                                            av0.2
NO PTL                                                                    307.755
BUS-ONLY PTL                                                               284.25
Best Daily HOV policy                                                     267.515
Best Daily HOV policy NAME                                                 Plus_3
Best HOV policy per scenario                                              267.325
Best HOV policy per scenario NAME                                          Plus_4
Best Daily StaticNumFL                                                     269.44
Best Daily StaticNumFL NAME                                     StaticNumPassFL_2
Best StaticNumFL per scenario                                              269.44
Best StaticNumFL per scenario NAME                              StaticNumPassFL_2
Best Daily Dynamic Policy                                                  281.89
Best Daily Dynamic Policy NAME                               Trained_TreesSimFeat
Best Dynamic Policy per scenario                                           253.35
Best Dynamic Policy per scenario NAME  ControlClipped mean_speed_in_end_PTL 13 20

                                                                    \
                                                             av0.3
NO PTL                                                      311.81
BUS-ONLY PTL                                                288.21
Best Daily HOV policy                                       280.08
Best Daily HOV policy NAME                                  Plus_3
Best HOV policy per scenario                                280.08
Best HOV policy per scenario NAME                           Plus_3
Best Daily StaticNumFL                                      260.22
Best Daily StaticNumFL NAME                      StaticNumPassFL_2
Best StaticNumFL per scenario                               260.22
Best StaticNumFL per scenario NAME               StaticNumPassFL_2
Best Daily Dynamic Policy                                   290.83
Best Daily Dynamic Policy NAME                Trained_TreesSimFeat
Best Dynamic Policy per scenario                            277.56
Best Dynamic Policy per scenario NAME  Trained_MLPRegressorSimFeat

                                                                      \
                                                               av0.4
NO PTL                                                       313.755
BUS-ONLY PTL                                                  289.69
Best Daily HOV policy                                         272.22
Best Daily HOV policy NAME                                    Plus_3
Best HOV policy per scenario                                  270.15
Best HOV policy per scenario NAME                             Plus_4
Best Daily StaticNumFL                                       266.325
Best Daily StaticNumFL NAME                        StaticNumPassFL_2
Best StaticNumFL per scenario                                266.325
Best StaticNumFL per scenario NAME                 StaticNumPassFL_2
Best Daily Dynamic Policy                                     282.01
Best Daily Dynamic Policy NAME                  Trained_TreesSimFeat