In [74]:
import pandas as pd
from pandas import MultiIndex

# Preparing LeftCompDaily

In [75]:
av_rates = ["av0.1", "av0.2", "av0.3", "av0.4", "av0.6", "av0.8"]

In [76]:
final_LeftCompDaily = pd.read_pickle("../results_csvs/scenarios_LeftCompDaily.pkl")
final_LeftCompDaily = final_LeftCompDaily["TOTAL"].drop(columns=["av0.5"])
final_LeftCompDaily.columns = MultiIndex.from_product([["LeftCompDaily"], final_LeftCompDaily.columns])
final_LeftCompDaily.dropna(inplace=True)

In [77]:
final_LeftCompDaily

                                LeftCompDaily                             \
                                        av0.1    av0.2    av0.3    av0.4
Control mean_speed_in_PTL 10 18       3771.36  3754.07  4506.08  5001.98
Control mean_speed_in_PTL 10 20       3702.08  3754.07  4506.08  5001.98
Control mean_speed_in_PTL 12 20        3622.7  3754.07  4506.08  5001.98
Control mean_speed_in_PTL 13 20       3702.08  3754.07  4506.08  5038.38
Control mean_speed_in_PTL 14 20       3702.08  3754.07  4506.08  5061.22
...                                       ...      ...      ...      ...
Trained_RFSimFeat                     3843.14  3733.72  3834.26   3723.5
Trained_Trees                         3813.19  3931.11  4297.31  4607.83
Trained_TreesSimFeat                  3676.56  3621.85  3554.58  3679.79
Trained_TreesSimFeatUnbounded         3766.14  3679.79  3914.57   4020.1
Trained_XGBoostSimFeat                3678.77  3729.96  3639.04  3783.55


                                   av0.6    av0.8
Control mean_speed_in_PTL 10 18  3913.36  3649.81
Control mean_speed_in_PTL 10 20  3915.56  3639.91
Control mean_speed_in_PTL 12 20  3863.04  3553.33
Control mean_speed_in_PTL 13 20  3808.12  3653.59
Control mean_speed_in_PTL 14 20  3783.92  3545.47
...                                  ...      ...
Trained_RFSimFeat                3956.48  4141.04
Trained_Trees                    4024.63  3969.58
Trained_TreesSimFeat             3558.54  3458.81
Trained_TreesSimFeatUnbounded    4248.16   4118.6
Trained_XGBoostSimFeat           4219.48  4048.31

[71 rows x 6 columns]

# Preparing LeftCompScenarios

In [78]:
final_LeftCompScenarios = pd.read_pickle("../results_csvs/scenarios_LeftCompScenarios.pkl")
final_LeftCompScenarios = final_LeftCompScenarios.drop(columns=["TOTAL"], level=0)
final_LeftCompScenarios.dropna(inplace=True)

In [79]:
final_LeftCompScenarios

                                RUSH_HOUR_EXT                             \
                                        av0.1    av0.2    av0.3    av0.4
Control mean_speed_in_PTL 10 18        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 10 20        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 12 20        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 13 20        489.46  494.595   537.17  596.745
Control mean_speed_in_PTL 14 20        489.46  494.595   537.17  596.745
...                                       ...      ...      ...      ...
Trained_RFSimFeat                     548.415   488.69  513.045    501.7
Trained_Trees                          528.52  542.755  533.695  580.415
Trained_TreesSimFeat                  503.065  523.535  538.735  507.155
Trained_TreesSimFeatUnbounded         511.525    532.8  535.925  499.145
Trained_XGBoostSimFeat                 502.42  492.775  516.815   529.41

                                                      PEAK                    \
                                   av0.6    av0.8    av0.1    av0.2    av0.3
Control mean_speed_in_PTL 10 18   532.73   523.66  758.005  767.205  810.835
Control mean_speed_in_PTL 10 20   532.73   523.66  758.005  767.205  810.835
Control mean_speed_in_PTL 12 20  516.375  559.095  758.005  767.205  810.835
Control mean_speed_in_PTL 13 20  516.375   556.84  758.005  767.205  810.835
Control mean_speed_in_PTL 14 20   526.67  548.925  758.005  767.205  810.835
...                                  ...      ...      ...      ...      ...
Trained_RFSimFeat                 523.28   571.18   780.08   742.15   815.16
Trained_Trees                     552.47   560.55  768.595   773.59  762.235
Trained_TreesSimFeat             513.455  490.215   804.35   757.64   782.02
Trained_TreesSimFeatUnbounded     543.32  556.025   790.43   770.89   769.37
Trained_XGBoostSimFeat           557.205    545.5  801.805  782.475  798.625

                                          ... WEEKEND                          \
                                   av0.4  ...   av0.3   av0.4   av0.6   av0.8
Control mean_speed_in_PTL 10 18  817.845  ...  18.415  18.225   16.98  17.695
Control mean_speed_in_PTL 10 20  817.845  ...  18.415  18.225   16.98  17.695
Control mean_speed_in_PTL 12 20  817.845  ...  18.415  18.225  17.185   17.35
Control mean_speed_in_PTL 13 20    835.5  ...  18.415  19.035  21.515   21.08
Control mean_speed_in_PTL 14 20    835.5  ...   18.28  19.035   17.68   18.64
...                                  ...  ...     ...     ...     ...     ...
Trained_RFSimFeat                829.485  ...   20.78  21.215  19.405   19.04
Trained_Trees                    824.465  ...  22.325  21.865   21.26   21.19
Trained_TreesSimFeat              799.96  ...   21.68  21.335  20.885  20.425
Trained_TreesSimFeatUnbounded    810.985  ...   19.63  21.185   20.45  19.945
Trained_XGBoostSimFeat           810.605  ...  20.615  20.855  21.125   21.02

                                MODERATE_RUSH_HOUR                             \
                                             av0.1    av0.2    av0.3    av0.4
Control mean_speed_in_PTL 10 18              246.2  249.425  380.935  409.625
Control mean_speed_in_PTL 10 20              246.2  249.425  380.935  409.625
Control mean_speed_in_PTL 12 20              246.2  249.425  380.935  409.625
Control mean_speed_in_PTL 13 20              246.2  249.425  380.935   405.04
Control mean_speed_in_PTL 14 20              246.2  249.425  360.275   405.04
...                                            ...      ...      ...      ...
Trained_RFSimFeat                          274.655  283.865  295.095   273.26
Trained_Trees                              260.215   279.96   358.43   354.97
Trained_TreesSimFeat                        282.84   275.97    286.6  273.255
Trained_TreesSimFeatUnbounded               281.77  272.345   300.18    296.9
Trained_XGBoostSimFeat                      282.38  269.155   286.66  295.175


                                   av0.6    av0.8
Control mean_speed_in_PTL 10 18   324.65   296.21
Control mean_speed_in_PTL 10 20  319.555    295.7
Control mean_speed_in_PTL 12 20  300.065   313.68
Control mean_speed_in_PTL 13 20    310.5    297.3
Control mean_speed_in_PTL 14 20  316.945   299.78
...                                  ...      ...
Trained_RFSimFeat                 309.86    324.4
Trained_Trees                     298.77   305.28
Trained_TreesSimFeat             268.425  262.705
Trained_TreesSimFeatUnbounded    298.655   296.97
Trained_XGBoostSimFeat            315.38  308.185

[71 rows x 30 columns]

# Preparing ClosedLeftCompScenarios

In [80]:
ClosedLeftCompScenarios = pd.read_pickle("../results_csvs/scenarios_ClosedLeftCompScenarios.pkl")
ClosedLeftCompScenarios = ClosedLeftCompScenarios.drop(columns=["TOTAL"], level=0)
ClosedLeftCompScenarios.dropna(inplace=True)

In [81]:
new_CloseLeftCompScenariosColumns = [("Closed_"+col[0], col[1]) for col in ClosedLeftCompScenarios.columns]
final_ClosedLeftCompScenarios = ClosedLeftCompScenarios.copy()
final_ClosedLeftCompScenarios.columns = MultiIndex.from_tuples(new_CloseLeftCompScenariosColumns)

In [82]:
final_ClosedLeftCompScenarios

                                Closed_RUSH_HOUR_EXT                    \
                                               av0.1    av0.2    av0.3
Control mean_speed_in_PTL 10 18               518.74   500.18  503.065
Control mean_speed_in_PTL 10 20               518.74   500.18  503.065
Control mean_speed_in_PTL 12 20               518.74   500.18  503.065
Control mean_speed_in_PTL 13 20               518.74   500.18  503.065
Control mean_speed_in_PTL 14 20               518.74   500.18  503.065
...                                              ...      ...      ...
Trained_RFSimFeat                            518.975  510.115  507.495
Trained_Trees                                  515.1  521.995    526.5
Trained_TreesSimFeat                          500.55   519.81   497.15
Trained_TreesSimFeatUnbounded                 518.76   500.61   497.83
Trained_XGBoostSimFeat                        512.05  512.145    501.6

                                                           Closed_PEAK  \
                                   av0.4    av0.6    av0.8       av0.1
Control mean_speed_in_PTL 10 18   569.81    568.7  566.885      783.11
Control mean_speed_in_PTL 10 20   569.81    568.7  566.885      783.11
Control mean_speed_in_PTL 12 20   569.81  562.555  545.345      783.11
Control mean_speed_in_PTL 13 20   569.81   560.36   536.38      783.11
Control mean_speed_in_PTL 14 20   569.81   560.36   525.16      783.11
...                                  ...      ...      ...         ...
Trained_RFSimFeat                  548.8   523.29    544.7     777.535
Trained_Trees                      539.4   514.53   560.37      759.07
Trained_TreesSimFeat             516.325    502.1   502.31      792.19
Trained_TreesSimFeatUnbounded    525.485  526.635   527.78      753.99
Trained_XGBoostSimFeat           496.235   545.54   541.81      775.52

                                                           ... Closed_WEEKEND  \
                                   av0.2    av0.3   av0.4  ...          av0.3
Control mean_speed_in_PTL 10 18   741.63  810.795  804.49  ...          19.96
Control mean_speed_in_PTL 10 20   741.63  810.795  804.49  ...          19.96
Control mean_speed_in_PTL 12 20   741.63  810.795  804.49  ...          19.02
Control mean_speed_in_PTL 13 20   741.63  810.795  804.49  ...          19.02
Control mean_speed_in_PTL 14 20  795.315  810.795  804.49  ...          19.02
...                                  ...      ...     ...  ...            ...
Trained_RFSimFeat                805.585    776.3  819.38  ...          20.89
Trained_Trees                     796.58   771.23  781.98  ...         21.555
Trained_TreesSimFeat              786.91    755.1   782.6  ...          21.17
Trained_TreesSimFeatUnbounded    766.955  772.195  781.52  ...          20.82
Trained_XGBoostSimFeat            769.89  794.315  842.52  ...          21.52

                                                         \
                                  av0.4   av0.6   av0.8
Control mean_speed_in_PTL 10 18  19.255  18.255  19.115
Control mean_speed_in_PTL 10 20  19.255  18.255  19.115
Control mean_speed_in_PTL 12 20  19.255   18.31  18.745
Control mean_speed_in_PTL 13 20  19.255  19.845   19.59
Control mean_speed_in_PTL 14 20   18.72   18.71   18.89
...                                 ...     ...     ...
Trained_RFSimFeat                20.515  19.215   19.07
Trained_Trees                     21.75   21.08   22.05
Trained_TreesSimFeat             21.665   20.67   20.09
Trained_TreesSimFeatUnbounded      20.4  20.685   21.48
Trained_XGBoostSimFeat            22.06   20.83   20.69

                                Closed_MODERATE_RUSH_HOUR                    \
                                                    av0.1    av0.2    av0.3
Control mean_speed_in_PTL 10 18                    269.08   273.84   343.16
Control mean_speed_in_PTL 10 20                    269.08   273.84   343.16
Control mean_speed_in_PTL 12 20                    269.08   273.84   371.25
Control mean_speed_in_PTL 13 20                    269.08   273.84   371.25
Control mean_speed_in_PTL 14 20                    269.08   265.25   371.25
...                                                   ...      ...      ...
Trained_RFSimFeat                                 289.425    284.8   288.71
Trained_Trees                                      289.02  296.075   291.96
Trained_TreesSimFeat                               306.03   281.89   290.83
Trained_TreesSimFeatUnbounded                     258.225  267.825  297.715
Trained_XGBoostSimFeat                            273.455  290.165  285.615


                                   av0.4    av0.6    av0.8
Control mean_speed_in_PTL 10 18   358.96   332.22  311.625
Control mean_speed_in_PTL 10 20   358.96   332.22  313.405
Control mean_speed_in_PTL 12 20  359.155  343.815  305.105
Control mean_speed_in_PTL 13 20   361.51  340.785  297.715
Control mean_speed_in_PTL 14 20    374.0   331.85  295.535
...                                  ...      ...      ...
Trained_RFSimFeat                276.835   264.27   294.38
Trained_Trees                     286.71  318.005    290.6
Trained_TreesSimFeat              282.01   273.23  283.465
Trained_TreesSimFeatUnbounded    271.675  273.715  284.665
Trained_XGBoostSimFeat            272.95  298.055   308.02

[71 rows x 30 columns]

# Creating the final results table

In [83]:
final_results_index =  ["NO PTL", "BUS-ONLY PTL", "Best Daily HOV policy", "Best HOV policy per scenario","Best Daily StaticNumFL", "Best StaticNumFL per scenario", "Best Daily Dynamic Policy", "Best Dynamic Policy per scenario"]
LeftCompDaily_empty = pd.DataFrame(columns=final_LeftCompDaily.columns, index=final_results_index)
LeftCompScenarios_empty = pd.DataFrame(columns=final_LeftCompScenarios.columns, index=final_results_index)
ClosedLeftCompScenarios_empty = pd.DataFrame(columns=final_ClosedLeftCompScenarios.columns, index=final_results_index)
final_results = pd.concat([LeftCompDaily_empty, LeftCompScenarios_empty, ClosedLeftCompScenarios_empty], axis=1)

In [84]:
final_results

                                 LeftCompDaily                                \
                                         av0.1 av0.2 av0.3 av0.4 av0.6 av0.8
NO PTL                                     NaN   NaN   NaN   NaN   NaN   NaN
BUS-ONLY PTL                               NaN   NaN   NaN   NaN   NaN   NaN
Best Daily HOV policy                      NaN   NaN   NaN   NaN   NaN   NaN
Best HOV policy per scenario               NaN   NaN   NaN   NaN   NaN   NaN
Best Daily StaticNumFL                     NaN   NaN   NaN   NaN   NaN   NaN
Best StaticNumFL per scenario              NaN   NaN   NaN   NaN   NaN   NaN
Best Daily Dynamic Policy                  NaN   NaN   NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario           NaN   NaN   NaN   NaN   NaN   NaN

                                 RUSH_HOUR_EXT                    ...  \
                                         av0.1 av0.2 av0.3 av0.4  ...
NO PTL                                     NaN   NaN   NaN   NaN  ...
BUS-ONLY PTL                               NaN   NaN   NaN   NaN  ...
Best Daily HOV policy                      NaN   NaN   NaN   NaN  ...
Best HOV policy per scenario               NaN   NaN   NaN   NaN  ...
Best Daily StaticNumFL                     NaN   NaN   NaN   NaN  ...
Best StaticNumFL per scenario              NaN   NaN   NaN   NaN  ...
Best Daily Dynamic Policy                  NaN   NaN   NaN   NaN  ...
Best Dynamic Policy per scenario           NaN   NaN   NaN   NaN  ...

                                 Closed_WEEKEND                    \
                                          av0.3 av0.4 av0.6 av0.8
NO PTL                                      NaN   NaN   NaN   NaN
BUS-ONLY PTL                                NaN   NaN   NaN   NaN
Best Daily HOV policy                       NaN   NaN   NaN   NaN
Best HOV policy per scenario                NaN   NaN   NaN   NaN
Best Daily StaticNumFL                      NaN   NaN   NaN   NaN
Best StaticNumFL per scenario               NaN   NaN   NaN   NaN
Best Daily Dynamic Policy                   NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario            NaN   NaN   NaN   NaN

                                 Closed_MODERATE_RUSH_HOUR                    \
                                                     av0.1 av0.2 av0.3 av0.4
NO PTL                                                 NaN   NaN   NaN   NaN
BUS-ONLY PTL                                           NaN   NaN   NaN   NaN
Best Daily HOV policy                                  NaN   NaN   NaN   NaN
Best HOV policy per scenario                           NaN   NaN   NaN   NaN
Best Daily StaticNumFL                                 NaN   NaN   NaN   NaN
Best StaticNumFL per scenario                          NaN   NaN   NaN   NaN
Best Daily Dynamic Policy                              NaN   NaN   NaN   NaN
Best Dynamic Policy per scenario                       NaN   NaN   NaN   NaN


                                 av0.6 av0.8
NO PTL                             NaN   NaN
BUS-ONLY PTL                       NaN   NaN
Best Daily HOV policy              NaN   NaN
Best HOV policy per scenario       NaN   NaN
Best Daily StaticNumFL             NaN   NaN
Best StaticNumFL per scenario      NaN   NaN
Best Daily Dynamic Policy          NaN   NaN
Best Dynamic Policy per scenario   NaN   NaN

[8 rows x 66 columns]

# adding no ptl and bus only ptl

In [85]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["NO PTL",col] = final_LeftCompScenarios.loc["Plus_1",col]
        final_results.loc["BUS-ONLY PTL",col] = final_LeftCompScenarios.loc["Nothing",col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["NO PTL",col] = final_LeftCompDaily.loc["Plus_1",col]
        final_results.loc["BUS-ONLY PTL",col] = final_LeftCompDaily.loc["Nothing",col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["NO PTL",col] = final_ClosedLeftCompScenarios.loc["Plus_1",col]
        final_results.loc["BUS-ONLY PTL",col] = final_ClosedLeftCompScenarios.loc["Nothing",col]

In [86]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                      NaN      NaN      NaN      NaN
Best HOV policy per scenario               NaN      NaN      NaN      NaN
Best Daily StaticNumFL                     NaN      NaN      NaN      NaN
Best StaticNumFL per scenario              NaN      NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN      NaN

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy                 NaN      NaN           NaN      NaN
Best HOV policy per scenario          NaN      NaN           NaN      NaN
Best Daily StaticNumFL                NaN      NaN           NaN      NaN
Best StaticNumFL per scenario         NaN      NaN           NaN      NaN
Best Daily Dynamic Policy             NaN      NaN           NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN           NaN      NaN

                                                   ... Closed_WEEKEND          \
                                    av0.3   av0.4  ...          av0.3   av0.4
NO PTL                            517.565  517.64  ...          20.06   20.38
BUS-ONLY PTL                      527.125  531.82  ...          21.19  21.605
Best Daily HOV policy                 NaN     NaN  ...            NaN     NaN
Best HOV policy per scenario          NaN     NaN  ...            NaN     NaN
Best Daily StaticNumFL                NaN     NaN  ...            NaN     NaN
Best StaticNumFL per scenario         NaN     NaN  ...            NaN     NaN
Best Daily Dynamic Policy             NaN     NaN  ...            NaN     NaN
Best Dynamic Policy per scenario      NaN     NaN  ...            NaN     NaN

                                               Closed_MODERATE_RUSH_HOUR  \
                                  av0.6  av0.8                     av0.1
NO PTL                            19.78  19.98                   308.725
BUS-ONLY PTL                      20.67  21.18                     286.1
Best Daily HOV policy               NaN    NaN                       NaN
Best HOV policy per scenario        NaN    NaN                       NaN
Best Daily StaticNumFL              NaN    NaN                       NaN
Best StaticNumFL per scenario       NaN    NaN                       NaN
Best Daily Dynamic Policy           NaN    NaN                       NaN
Best Dynamic Policy per scenario    NaN    NaN                       NaN


                                    av0.2   av0.3    av0.4    av0.6    av0.8
NO PTL                            307.755  311.81  313.755  310.965  305.155
BUS-ONLY PTL                       284.25  288.21   289.69  285.615   289.49
Best Daily HOV policy                 NaN     NaN      NaN      NaN      NaN
Best HOV policy per scenario          NaN     NaN      NaN      NaN      NaN
Best Daily StaticNumFL                NaN     NaN      NaN      NaN      NaN
Best StaticNumFL per scenario         NaN     NaN      NaN      NaN      NaN
Best Daily Dynamic Policy             NaN     NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario      NaN     NaN      NaN      NaN      NaN

[8 rows x 66 columns]

# Adding best daily HOV policy

In [87]:
def row_with_max_min_count(df):
    min_values = df.min()
    is_min = df.eq(min_values)
    min_count_per_row = is_min.sum(axis=1)
    row_with_most_min_values = min_count_per_row.idxmax()
    return row_with_most_min_values

In [88]:
HOVs = ["Plus_1", "Plus_2", "Plus_3", "Plus_4", "Plus_5"]
LeftCompDaily_HOVs =  final_LeftCompDaily.loc[HOVs]
LeftCompDaily_HOVs_idx = row_with_max_min_count(LeftCompDaily_HOVs)
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Daily HOV policy",col] = final_LeftCompScenarios.loc[LeftCompDaily_HOVs_idx,col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Daily HOV policy",col] = final_LeftCompDaily.loc[LeftCompDaily_HOVs_idx,col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Daily HOV policy",col] = final_ClosedLeftCompScenarios.loc[LeftCompDaily_HOVs_idx,col]

In [89]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario               NaN      NaN      NaN      NaN
Best Daily StaticNumFL                     NaN      NaN      NaN      NaN
Best StaticNumFL per scenario              NaN      NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN      NaN

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario          NaN      NaN           NaN      NaN
Best Daily StaticNumFL                NaN      NaN           NaN      NaN
Best StaticNumFL per scenario         NaN      NaN           NaN      NaN
Best Daily Dynamic Policy             NaN      NaN           NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN           NaN      NaN

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario          NaN      NaN  ...            NaN
Best Daily StaticNumFL                NaN      NaN  ...            NaN
Best StaticNumFL per scenario         NaN      NaN  ...            NaN
Best Daily Dynamic Policy             NaN      NaN  ...            NaN
Best Dynamic Policy per scenario      NaN      NaN  ...            NaN

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario         NaN     NaN     NaN
Best Daily StaticNumFL               NaN     NaN     NaN
Best StaticNumFL per scenario        NaN     NaN     NaN
Best Daily Dynamic Policy            NaN     NaN     NaN
Best Dynamic Policy per scenario     NaN     NaN     NaN

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                           NaN      NaN     NaN
Best Daily StaticNumFL                                 NaN      NaN     NaN
Best StaticNumFL per scenario                          NaN      NaN     NaN
Best Daily Dynamic Policy                              NaN      NaN     NaN
Best Dynamic Policy per scenario                       NaN      NaN     NaN


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario          NaN      NaN      NaN
Best Daily StaticNumFL                NaN      NaN      NaN
Best StaticNumFL per scenario         NaN      NaN      NaN
Best Daily Dynamic Policy             NaN      NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN      NaN

[8 rows x 66 columns]

# Adding best HOV policy per scenario

In [90]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best HOV policy per scenario",col] = final_LeftCompScenarios[col].loc[HOVs].min()
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best HOV policy per scenario",col] = final_LeftCompDaily[col].loc[HOVs].min()
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best HOV policy per scenario",col] = final_ClosedLeftCompScenarios[col].loc[HOVs].min()

In [91]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario           3523.02  3529.48  3490.59  3597.59
Best Daily StaticNumFL                     NaN      NaN      NaN      NaN
Best StaticNumFL per scenario              NaN      NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN      NaN

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario      3555.74  3490.04       485.255  500.865
Best Daily StaticNumFL                NaN      NaN           NaN      NaN
Best StaticNumFL per scenario         NaN      NaN           NaN      NaN
Best Daily Dynamic Policy             NaN      NaN           NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN           NaN      NaN

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario      514.345  505.375  ...           19.6
Best Daily StaticNumFL                NaN      NaN  ...            NaN
Best StaticNumFL per scenario         NaN      NaN  ...            NaN
Best Daily Dynamic Policy             NaN      NaN  ...            NaN
Best Dynamic Policy per scenario      NaN      NaN  ...            NaN

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario       19.08  19.225   19.42
Best Daily StaticNumFL               NaN     NaN     NaN
Best StaticNumFL per scenario        NaN     NaN     NaN
Best Daily Dynamic Policy            NaN     NaN     NaN
Best Dynamic Policy per scenario     NaN     NaN     NaN

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                        272.37  267.325  280.08
Best Daily StaticNumFL                                 NaN      NaN     NaN
Best StaticNumFL per scenario                          NaN      NaN     NaN
Best Daily Dynamic Policy                              NaN      NaN     NaN
Best Dynamic Policy per scenario                       NaN      NaN     NaN


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario       270.15  262.985   272.56
Best Daily StaticNumFL                NaN      NaN      NaN
Best StaticNumFL per scenario         NaN      NaN      NaN
Best Daily Dynamic Policy             NaN      NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN      NaN

[8 rows x 66 columns]

# Adding best daily StaticNumFL

In [92]:
StaticNumFLs = [f"StaticNumPassFL_{i}" for i in range(1,6)]
LeftCompDaily_StaticNumFLs =  final_LeftCompDaily.loc[StaticNumFLs]
LeftCompDaily_StaticNumFLs_idx = row_with_max_min_count(LeftCompDaily_StaticNumFLs)
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Daily StaticNumFL",col] = final_LeftCompScenarios.loc[LeftCompDaily_StaticNumFLs_idx,col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Daily StaticNumFL",col] = final_LeftCompDaily.loc[LeftCompDaily_StaticNumFLs_idx,col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Daily StaticNumFL",col] = final_ClosedLeftCompScenarios.loc[LeftCompDaily_StaticNumFLs_idx,col]

In [93]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario           3523.02  3529.48  3490.59  3597.59
Best Daily StaticNumFL                 3589.44  3644.66  3486.99  3600.17
Best StaticNumFL per scenario              NaN      NaN      NaN      NaN
Best Daily Dynamic Policy                  NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN      NaN

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario      3555.74  3490.04       485.255  500.865
Best Daily StaticNumFL             3853.2   4364.4       519.845   501.59
Best StaticNumFL per scenario         NaN      NaN           NaN      NaN
Best Daily Dynamic Policy             NaN      NaN           NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN           NaN      NaN

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario      514.345  505.375  ...           19.6
Best Daily StaticNumFL            525.825  491.355  ...           20.6
Best StaticNumFL per scenario         NaN      NaN  ...            NaN
Best Daily Dynamic Policy             NaN      NaN  ...            NaN
Best Dynamic Policy per scenario      NaN      NaN  ...            NaN

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario       19.08  19.225   19.42
Best Daily StaticNumFL            20.625  19.235    19.3
Best StaticNumFL per scenario        NaN     NaN     NaN
Best Daily Dynamic Policy            NaN     NaN     NaN
Best Dynamic Policy per scenario     NaN     NaN     NaN

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                        272.37  267.325  280.08
Best Daily StaticNumFL                             271.885   269.44  260.22
Best StaticNumFL per scenario                          NaN      NaN     NaN
Best Daily Dynamic Policy                              NaN      NaN     NaN
Best Dynamic Policy per scenario                       NaN      NaN     NaN


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario       270.15  262.985   272.56
Best Daily StaticNumFL            266.325   299.09   332.73
Best StaticNumFL per scenario         NaN      NaN      NaN
Best Daily Dynamic Policy             NaN      NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN      NaN

[8 rows x 66 columns]

# Adding best StaticNumFL per scenario

In [94]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best StaticNumFL per scenario",col] = final_LeftCompScenarios[col].loc[StaticNumFLs].min()
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best StaticNumFL per scenario",col] = final_LeftCompDaily[col].loc[StaticNumFLs].min()
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best StaticNumFL per scenario",col] = final_ClosedLeftCompScenarios[col].loc[StaticNumFLs].min()

In [95]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario           3523.02  3529.48  3490.59  3597.59
Best Daily StaticNumFL                 3589.44  3644.66  3486.99  3600.17
Best StaticNumFL per scenario          3589.44  3644.66  3486.99  3600.17
Best Daily Dynamic Policy                  NaN      NaN      NaN      NaN
Best Dynamic Policy per scenario           NaN      NaN      NaN      NaN

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario      3555.74  3490.04       485.255  500.865
Best Daily StaticNumFL             3853.2   4364.4       519.845   501.59
Best StaticNumFL per scenario     3488.79  3570.62        489.46  494.595
Best Daily Dynamic Policy             NaN      NaN           NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN           NaN      NaN

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario      514.345  505.375  ...           19.6
Best Daily StaticNumFL            525.825  491.355  ...           20.6
Best StaticNumFL per scenario      485.36  491.355  ...          19.96
Best Daily Dynamic Policy             NaN      NaN  ...            NaN
Best Dynamic Policy per scenario      NaN      NaN  ...            NaN

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario       19.08  19.225   19.42
Best Daily StaticNumFL            20.625  19.235    19.3
Best StaticNumFL per scenario     19.255  19.055  19.065
Best Daily Dynamic Policy            NaN     NaN     NaN
Best Dynamic Policy per scenario     NaN     NaN     NaN

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                        272.37  267.325  280.08
Best Daily StaticNumFL                             271.885   269.44  260.22
Best StaticNumFL per scenario                       269.08   269.44  260.22
Best Daily Dynamic Policy                              NaN      NaN     NaN
Best Dynamic Policy per scenario                       NaN      NaN     NaN


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario       270.15  262.985   272.56
Best Daily StaticNumFL            266.325   299.09   332.73
Best StaticNumFL per scenario     266.325  272.665   249.16
Best Daily Dynamic Policy             NaN      NaN      NaN
Best Dynamic Policy per scenario      NaN      NaN      NaN

[8 rows x 66 columns]

# Adding best daily Dynamic Policy

In [96]:
DynamicPolicies = list(set(final_LeftCompScenarios.index.tolist())-set(HOVs+StaticNumFLs+["Nothing"]))
LeftCompDaily_DynamicPolicies =  final_LeftCompDaily.loc[DynamicPolicies]
LeftCompDaily_DynamicPolicies_idx = row_with_max_min_count(LeftCompDaily_DynamicPolicies)
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Daily Dynamic Policy",col] = final_LeftCompScenarios.loc[LeftCompDaily_DynamicPolicies_idx,col]
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Daily Dynamic Policy",col] = final_LeftCompDaily.loc[LeftCompDaily_DynamicPolicies_idx,col]
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Daily Dynamic Policy",col] = final_ClosedLeftCompScenarios.loc[LeftCompDaily_DynamicPolicies_idx,col]

In [97]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario           3523.02  3529.48  3490.59  3597.59
Best Daily StaticNumFL                 3589.44  3644.66  3486.99  3600.17
Best StaticNumFL per scenario          3589.44  3644.66  3486.99  3600.17
Best Daily Dynamic Policy              3676.56  3621.85  3554.58  3679.79
Best Dynamic Policy per scenario           NaN      NaN      NaN      NaN

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario      3555.74  3490.04       485.255  500.865
Best Daily StaticNumFL             3853.2   4364.4       519.845   501.59
Best StaticNumFL per scenario     3488.79  3570.62        489.46  494.595
Best Daily Dynamic Policy         3558.54  3458.81       503.065  523.535
Best Dynamic Policy per scenario      NaN      NaN           NaN      NaN

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario      514.345  505.375  ...           19.6
Best Daily StaticNumFL            525.825  491.355  ...           20.6
Best StaticNumFL per scenario      485.36  491.355  ...          19.96
Best Daily Dynamic Policy         538.735  507.155  ...          21.17
Best Dynamic Policy per scenario      NaN      NaN  ...            NaN

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario       19.08  19.225   19.42
Best Daily StaticNumFL            20.625  19.235    19.3
Best StaticNumFL per scenario     19.255  19.055  19.065
Best Daily Dynamic Policy         21.665   20.67   20.09
Best Dynamic Policy per scenario     NaN     NaN     NaN

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                        272.37  267.325  280.08
Best Daily StaticNumFL                             271.885   269.44  260.22
Best StaticNumFL per scenario                       269.08   269.44  260.22
Best Daily Dynamic Policy                           306.03   281.89  290.83
Best Dynamic Policy per scenario                       NaN      NaN     NaN


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario       270.15  262.985   272.56
Best Daily StaticNumFL            266.325   299.09   332.73
Best StaticNumFL per scenario     266.325  272.665   249.16
Best Daily Dynamic Policy          282.01   273.23  283.465
Best Dynamic Policy per scenario      NaN      NaN      NaN

[8 rows x 66 columns]

# Adding best Dynamic Policy per scenario

In [98]:
for col in final_results.columns:
    if col in final_LeftCompScenarios.columns:
        final_results.loc["Best Dynamic Policy per scenario",col] = final_LeftCompScenarios[col].loc[DynamicPolicies].min()
    elif col in final_LeftCompDaily.columns:
        final_results.loc["Best Dynamic Policy per scenario",col] = final_LeftCompDaily[col].loc[DynamicPolicies].min()
    elif col in final_ClosedLeftCompScenarios.columns:
        final_results.loc["Best Dynamic Policy per scenario",col] = final_ClosedLeftCompScenarios[col].loc[DynamicPolicies].min()

In [99]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario           3523.02  3529.48  3490.59  3597.59
Best Daily StaticNumFL                 3589.44  3644.66  3486.99  3600.17
Best StaticNumFL per scenario          3589.44  3644.66  3486.99  3600.17
Best Daily Dynamic Policy              3676.56  3621.85  3554.58  3679.79
Best Dynamic Policy per scenario       3524.88  3621.85  3554.58  3679.79

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario      3555.74  3490.04       485.255  500.865
Best Daily StaticNumFL             3853.2   4364.4       519.845   501.59
Best StaticNumFL per scenario     3488.79  3570.62        489.46  494.595
Best Daily Dynamic Policy         3558.54  3458.81       503.065  523.535
Best Dynamic Policy per scenario  3558.54  3458.81       488.875   488.69

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario      514.345  505.375  ...           19.6
Best Daily StaticNumFL            525.825  491.355  ...           20.6
Best StaticNumFL per scenario      485.36  491.355  ...          19.96
Best Daily Dynamic Policy         538.735  507.155  ...          21.17
Best Dynamic Policy per scenario  508.185  499.145  ...          18.45

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario       19.08  19.225   19.42
Best Daily StaticNumFL            20.625  19.235    19.3
Best StaticNumFL per scenario     19.255  19.055  19.065
Best Daily Dynamic Policy         21.665   20.67   20.09
Best Dynamic Policy per scenario  18.435   17.68  18.135

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                        272.37  267.325  280.08
Best Daily StaticNumFL                             271.885   269.44  260.22
Best StaticNumFL per scenario                       269.08   269.44  260.22
Best Daily Dynamic Policy                           306.03   281.89  290.83
Best Dynamic Policy per scenario                   258.225   253.35  277.56


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario       270.15  262.985   272.56
Best Daily StaticNumFL            266.325   299.09   332.73
Best StaticNumFL per scenario     266.325  272.665   249.16
Best Daily Dynamic Policy          282.01   273.23  283.465
Best Dynamic Policy per scenario  271.675   264.27   265.79

[8 rows x 66 columns]

In [108]:
# Highlight the min in each row
def highlight_min(s):
    # filter out indices that contain HOV
    s_without = s[~s.index.str.contains("HOV")]
    is_min = s == s.min()
    is_min_without = s == s_without.min()
    styles = []
    # set to bold and yellow if it is the min
    for v,u in zip(is_min, is_min_without):
        style = ''
        if v and u:
            style = 'background-color: yellow; font-weight: bold'
        elif v:
            style = 'background-color: yellow'
        elif u:
            style = 'font-weight: bold' 
        styles.append(style)
    return styles
final_results.style.apply(highlight_min, axis=0).to_excel("final_results.xlsx")

In [103]:
final_results

                                 LeftCompDaily                             \
                                         av0.1    av0.2    av0.3    av0.4
NO PTL                                 4299.88  4300.38  4306.26  4306.22
BUS-ONLY PTL                           3959.38  3959.71  3962.75  3964.21
Best Daily HOV policy                  3523.02  3529.48  3490.59  3597.59
Best HOV policy per scenario           3523.02  3529.48  3490.59  3597.59
Best Daily StaticNumFL                 3589.44  3644.66  3486.99  3600.17
Best StaticNumFL per scenario          3589.44  3644.66  3486.99  3600.17
Best Daily Dynamic Policy              3676.56  3621.85  3554.58  3679.79
Best Dynamic Policy per scenario       3524.88  3621.85  3554.58  3679.79

                                                   RUSH_HOUR_EXT           \
                                    av0.6    av0.8         av0.1    av0.2
NO PTL                            4300.79   4299.4        517.95   520.21
BUS-ONLY PTL                      3961.77  3958.67       523.465  527.125
Best Daily HOV policy             3636.39  3581.58       485.255  515.675
Best HOV policy per scenario      3555.74  3490.04       485.255  500.865
Best Daily StaticNumFL             3853.2   4364.4       519.845   501.59
Best StaticNumFL per scenario     3488.79  3570.62        489.46  494.595
Best Daily Dynamic Policy         3558.54  3458.81       503.065  523.535
Best Dynamic Policy per scenario  3558.54  3458.81       488.875   488.69

                                                    ... Closed_WEEKEND  \
                                    av0.3    av0.4  ...          av0.3
NO PTL                            517.565   517.64  ...          20.06
BUS-ONLY PTL                      527.125   531.82  ...          21.19
Best Daily HOV policy             514.345  511.655  ...          21.28
Best HOV policy per scenario      514.345  505.375  ...           19.6
Best Daily StaticNumFL            525.825  491.355  ...           20.6
Best StaticNumFL per scenario      485.36  491.355  ...          19.96
Best Daily Dynamic Policy         538.735  507.155  ...          21.17
Best Dynamic Policy per scenario  508.185  499.145  ...          18.45

                                                          \
                                   av0.4   av0.6   av0.8
NO PTL                             20.38   19.78   19.98
BUS-ONLY PTL                      21.605   20.67   21.18
Best Daily HOV policy             21.075  19.915  20.915
Best HOV policy per scenario       19.08  19.225   19.42
Best Daily StaticNumFL            20.625  19.235    19.3
Best StaticNumFL per scenario     19.255  19.055  19.065
Best Daily Dynamic Policy         21.665   20.67   20.09
Best Dynamic Policy per scenario  18.435   17.68  18.135

                                 Closed_MODERATE_RUSH_HOUR                   \
                                                     av0.1    av0.2   av0.3
NO PTL                                             308.725  307.755  311.81
BUS-ONLY PTL                                         286.1   284.25  288.21
Best Daily HOV policy                               272.37  267.515  280.08
Best HOV policy per scenario                        272.37  267.325  280.08
Best Daily StaticNumFL                             271.885   269.44  260.22
Best StaticNumFL per scenario                       269.08   269.44  260.22
Best Daily Dynamic Policy                           306.03   281.89  290.83
Best Dynamic Policy per scenario                   258.225   253.35  277.56


                                    av0.4    av0.6    av0.8
NO PTL                            313.755  310.965  305.155
BUS-ONLY PTL                       289.69  285.615   289.49
Best Daily HOV policy              272.22  262.985   275.95
Best HOV policy per scenario       270.15  262.985   272.56
Best Daily StaticNumFL            266.325   299.09   332.73
Best StaticNumFL per scenario     266.325  272.665   249.16
Best Daily Dynamic Policy          282.01   273.23  283.465
Best Dynamic Policy per scenario  271.675   264.27   265.79

[8 rows x 66 columns]